### ISSUE TITLE
MediaSession

### ISSUE THREAD

**Issue by xxyzzzq** [w3ctag/design-reviews#149]
Hello TAG!

I'm requesting a TAG review of:

  - Name: MediaSession API
  - Specification URL: https://wicg.github.io/mediasession/
  - Explainer: https://github.com/WICG/mediasession/blob/master/explainer.md
  - Example code:
    - https://xxyzzzq.github.io/sandbox/media-session/full-test.html
    - https://beaufortfrancois.github.io/sandbox/media-session/playground.html
  - Primary contacts: @xxyzzzq @mounirlamouri

Further details (optional):

  - Relevant time constraints or deadlines: we would like to ship in Chrome M-57, so preferably before Feburary.
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/WICG/mediasession/blob/master/security-privacy-questionnaire.md).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify

**Comment by travisleithead** [comment]
@slightlyoff notes: there should be by-design similarity to image file types from Notifications API & Manifest file. We should avoid proliferating types of image metadata formats...

**Comment by travisleithead** [comment]
Explainer looks nice! All the following feedback is based on reading the explainer...

1. The term MediaSession seems odd given what the feature does (I acknowledge that this comes from Andriod). Seems more like a "Media Control Extensions"
2. metaData and playbackState, do these represent the last set value or the state that the UA is in? These may need to be Async if the APIs will represent the UA's current state.
3. Should 'muted' be included in the MediaSessionAction enum? e.g., many browsers have an option to 'mute' a tab--is this a scenario that should be included?
4. For the 'artwork' (MediaImage), are these the right members for good responsive image design? Have the RICG folks been contacted? I think they'd have a good perspective.
5. Might be nice to be able to have more direct control over a particular action-handler, e.g., especially for the play/pause state changes. E.g., is there an opportunity to provide input for an action handler, as opposed to just metadata input?
6. No way to unsetActionHandler? What happens if you set the same action handler twice?
7. There's lots of potential metadata to include, how/why did you pick this particular subset? e.g., why not genre, year, etc.? (Not sure if you saw this 2014 Recommendation "Metadata API for Media Resources 1.0"? http://www.w3.org/TR/2014/REC-mediaont-api-1.0-20140313/. It's part of the Semantic-web line of documents, but does have some specific metadata fields that might be thoughtfully considered.)
8. Have the "remote playback API" folks been contacted? There may be an opportunity to unify some of  these concepts with those concepts? (https://github.com/w3ctag/spec-reviews/issues/145)
9. MediaSession as global instance... various platforms will certainly have their conventions. The management of mediaSession between a single apps iframes and between multiple tabs in a browser environment seem like essentially the same problem. If there is a security concern then consider [SecureContext], but otherwise, I wonder if adding author-management for this complexity is worth the effort. I have a hunch UA's will do the right thing, and even if they don't, the OS will need to do the right thing when brokering access between Apps and sites (even in different browsers) all competing for the mediasession instance. I'm not sure to what extent it makes sense to try to solve this problem in the spec.

**Comment by xxyzzzq** [comment]
Thanks for the feedback, I'm replying to these individual issues.

**Comment by travisleithead** [comment]
Our pleasure! Keeping this issue open--we'll check-in again at our next F2F to see how the individual linked issues are coming along. Thanks again--we're very happy to be able to help!

**Comment by travisleithead** [comment]
I'll be following up on the individual issues. We are otherwise done with this parent review issue. Thanks for asking for TAG review!
