### ISSUE TITLE
Long Task API

### ISSUE THREAD

**Issue by spanicker** [w3ctag/design-reviews#150]
Hello TAG!

I'm requesting a TAG review of:

  - Name: Long Task API
  - Specification URL: https://wicg.github.io/longtasks/
  - Explainer, Requirements Doc, or Example code: https://github.com/wicg/longtasks/
  - Primary contacts: spanicker, igrigorik, domenic

Further details (optional):

  - Relevant time constraints or deadlines: Feb 28 would be ideal, we'd like to ship in Chrome M58
  - I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1tIMI1gau_q6X5EBnjDNiFS5NWV9cpYJ5KKA7xPd3VB8/edit)
  - I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):
  - [YES] open issues in our Github repo for each point of feedback

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, some decent explainers:

  https://github.com/w3c/ServiceWorker/blob/master/explainer.md
  https://github.com/zkoch/paymentrequest/blob/gh-pages/docs/explainer.md
  https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md (although this one includes IDL, which an explainer should not)

**Comment by torgo** [comment]
Discussed in Boston f2f 8-feb-2017.

**Comment by torgo** [comment]
Potential developer frustration at lack of precision, but this is to preserve user privacy.

**Comment by torgo** [comment]
Is there an explainer?

**Comment by slightlyoff** [comment]
Hey @spanicker,

Thanks for filing this and working with us! We read the spec at the F2F meeting in Tokyo and are happy with the shape of the API. @torgo's note about the lack of precision was part of a conversation discussing the design constraints. Overall, we're happy with how this has turned out and want to see it move forward.

Consider this a "clean bill of health" on the design, although we would note that a spec like this should have an explainer which outlines the problems it solves and shows example code for how the issues are addressed by the design. This will continue to be important as you look towards V2. 

Thanks for looking into that and bringing us into your design process.

Regards

**Comment by spanicker** [comment]
Thanks for the feedback, I'll keep that in mind going forward.

BTW The explainer is here: https://github.com/w3c/longtasks/
