### ISSUE TITLE
Request to review First Paint Timing

### ISSUE THREAD

**Issue by spanicker** [w3ctag/design-reviews#177]
Hello TAG!

I'm requesting a TAG review of:

  - Name: First Paint Timing
  - Specification URL: https://github.com/WICG/paint-timing
  - Explainer: https://github.com/WICG/paint-timing
  - Primary contacts: spanicker, tdresser

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open a single issue in our Github repo for the entire review

--------------------------

_Please preview the issue and check that the links work before submitting_

**Comment by dbaron** [comment]
Is there a URL to view the specification on the Web, or does it require cloning the repository?  The repo doesn't seem to be set up for GitHub Pages.

**Comment by domenic** [comment]
Based on the mostly-empty index.html, I think @spanicker is asking for review of the explainer, in an attempt to get TAG involvement earlier in the process?

**Comment by domenic** [comment]
Oh, right, I'm remembering now. There is no spec yet, but the plan is at https://github.com/WICG/paint-timing/issues/4

**Comment by dbaron** [comment]
So there's some discussion in the linked [Why First Paint as Web Perf API?](https://docs.google.com/document/d/1wdxSXo_jctZjdPaJeTtYYFF-rLtUFxrU72_7h9qbQaM/edit) document about the relative value of `first-paint` versus `first-contentful-paint`, pointing out that:
> FP should be monitored by developers as a top level Progress Metric in addition to FCP.
> FP is still necessary even if we have FCP. FP is the first major feedback to the user that “It is happening”. It indicates that the “browser has started rendering”. 
> FCP is less reliable for this first visual indication, because it can move due to adding some minor contentful but meaningless thing such as a copyright image.

This makes me wonder how useful `first-content-paint` is overall.

Was there consideration of adding an API that allows developers to request first-paint data (maybe separately for background, image, text, etc.) for a specific element that they care about the painting of, rather than the potentially-volatile `first-contentful-paint`?  (Does that make things a lot harder, or just a little harder?)

**Comment by spanicker** [comment]
From field data developers have reported that FCP is very useful for them.
Yes there is in fact a proposal for adding an API that allows developers to request first-paint for specific element:
https://docs.google.com/document/d/1yRYfYR1DnHtgwC4HRR04ipVVhT1h5gkI6yPmKCgJkyQ/edit
However it is will take a long time to implement and get right for all the myriad cases (image, svg, font etc), it's quite a lot harder than FCP.

**Comment by triblondon** [comment]
Taken up at London F2F.  We think this looks great and have no substantive feedback.

**Comment by NE-SmallTown** [comment]
Hi, can I ask that why there is 'have no substantive feedback', it looks like chrome has implemented this

**Comment by NE-SmallTown** [comment]
Hi, can I ask that why there is 'have no substantive feedback', it looks like chrome has implemented this?
