### ISSUE TITLE
Serialization of natural language in data formats such as JSON [I18N]

### ISSUE THREAD

**Issue by aphillips** [w3ctag/design-reviews#178]
Hello TAG!

I'm requesting a TAG review of:

  - Name: [Recommendations for language and direction attributes in data formats](http://w3c.github.io/i18n-discuss/notes/i18n-action-612.html) **_This document is an explainer._**
  - Primary contacts: [@aphillips][@r12a]

Further details (optional):

  - Relevant time constraints or deadlines: None specifically, but this has been a developing problem for us.

You should also know that...

The Internationalization WG has been commenting on data format specifications with increasing frequency over the past couple years in which we have noted the lack of natural language string types in formats such as JSON. We are concerned that there are internationalization gaps or, in an attempt to address our comments, non-interoperable and divergent implementation choices being made.

This issue is the result of an [I18N WG action](https://www.w3.org/International/track/actions/552). 

We would like the TAG's opinion on the problem and mooted solutions. The I18N WG chair (@aphillips) and Team contact (@r12a) can be available for consultation as needed.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [X] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [@aphillips][@r12a]

**Comment by aphillips** [comment]
Please add the i18n-discuss label so that our tracking mechanism picks this up.

**Comment by domenic** [comment]
This seems related to the discussion currently happening in https://github.com/heycam/webidl/pull/358, where we're attempting to add a shared primitive to Web IDL that all specs can use, and getting stuck. The point of contention is basically whether the pattern should be

```js
someAPI({
  lang: "...",
  dir: "...",
  label: "a string governed by the lang/dir"
  name: "another string, governed by the same lang/dir"
});
```

(the "`Localizable` base dictionary" solution)

or

```js
someAPI({
  label: {
    lang: "...",
    dir: "...",
    value: "a string governed by the lang/dir"
  },
  name: "another string, using the default lang/dir"
});
```

(the "`LocalizableString` union typedef" solution).

The former makes it easier to say that all strings have the same lang/dir. The latter allows more granular decision making, at the cost of verbosity.

I suppose you could even have both.

**Comment by r12a** [comment]
@aphillips it seems that this repo is not under the w3c/ domain, so i'm unable to set up the normal notifications and labels, and we won't get notifications to our list.

**Comment by dbaron** [comment]
One question we're thinking about is to what extent this can be solved by using only dir="auto" (plus LRM and RLM or similar) and [language tags](http://unicode.org/faq/languagetagging.html).  The ergonomics of both options aren't great.  I also wonder whether there's an alternative that could be plain text much of the time but could also be more markup-like when needed.

**Comment by torgo** [comment]
Discussed on [call 06-06](https://github.com/w3ctag/meetings/blob/gh-pages/2017/telcons/06-06-agenda.md) suggestion that I18N group should work with WebIDL group.

**Comment by cynthia** [comment]
> Solution 1: New Data Type
> Create a new data type whose serialization optionally includes language and direction. Examples:
> 
>	myLocalizedString: "Hello World!"@en^ltr
>	myLocalizedString_fr: "Bonjour monde !"@fr
>	myLocalizedString_ar: "مرحبا بالعالم!"@ar-EG^rtl
>	myLocalizedString_und: "שלום עולם!"^rtl
>	myLanguageNeutralString: "978-0-123-4567-X" // no language or direction for this non-natural-language string

There are quite a few parser implementations out in the wild already for this approach to be feasible - and since parsers which do not support this feature will not function against data with these tags present, this does not seem like a way forward.

We did briefly touch on http://unicode.org/faq/languagetagging.html during the call, in case that would be an option.

**Comment by aphillips** [comment]
dir="auto" is not a panacea. The first strong characters in a string may be left-to-right and fool the algorithm. 

My concern here is that this requires the addition of LRM/RLM markers to data---data that may not be owned by the process assembling the wire format or that may have a field length restriction expressed in characters, code units, or bytes, etc. Adopting auto semantics and requiring the markers introduces (possibly cascading) data change. It also requires, in some cases, developers to introduce more markers into text, as when assembling messages.

**Comment by aphillips** [comment]
@cynthia The Unicode language tagging characters are deprecated and it is a Bad Idea to use them. We knew coming in that a new data type was more-or-less a non-starter unless/until our request for the keys to the time machine comes through.

@torgo Thanks for the update. We'll reach out to WebIDL

**Comment by r12a** [comment]
All, wrt using Unicode formatting characters to establish direction, please read the other docs that Addison links – in particular  http://w3c.github.io/i18n-discuss/notes/string-base-direction.html – where we try to enumerate the pros and cons of various approaches.  (@aphilips we should probably make it a bit clearer that folks should read those docs to get a better basis for discussion)

@domenic it's useful to be able to apply the same lang/dir metadata to multiple strings without repeating the metadata, if that's possible; however, it's certainly easy to imagine situations where different assignments are needed for particular strings (eg. in the case of a set of alternative translations for an error message, where one string is in english, and another in hebrew).

hth

**Comment by cynthia** [comment]
> The Unicode language tagging characters are deprecated and it is a Bad Idea to use them. We knew coming in that a new data type was more-or-less a non-starter unless/until our request for the keys to the time machine comes through.

Understood. It was just a note that the topic came up during the call.

**Comment by dbaron** [comment]
So let me present what I'm concerned about here in a little more detail.  My basic concern is that there really don't seem to be any good options:
* the new data type seems to be a non-starter in terms of compatibility (e.g., parsing, etc.)
* the use of dictionaries makes things harder for both developers using the API, for implementors of the API, and for specification authors (increasing both the amount of work and the risk of errors) and:
  * if the use of a dictionary rather than a string is option, the handling of dictionaries is frequently going to be wrong in both specs and implementations.
  * if the use of a dictionary is not optional, it adds a good bit of extra overhead for developers in the common case where they're not going to be interested in adding language or direction information.

One of the pieces of advice from i18n in the past was that text that should be presented to users should be markup rather than attribute values, so that when needed it could allow elements within it (for things like language and direction, ruby, etc.).  I also wonder whether this sort of advice could be extended here, i.e., whether we should be encouraging the use of HTML rather than text.

**Comment by dbaron** [comment]
(And if we wanted to encourage HTML, would it be a subset of HTML, or arbitrary HTML?)

**Comment by aphillips** [comment]
Thanks @dbaron. While, in general, markup is a Good Thing for this, at the same time the point of using JSON and other data languages is the transmission of "unrendered" data. Let me give a concrete use case.

Suppose that in my day job I am building a Web page to show a customer's library of e-books. The e-books exist in a catalog of data and consist of the usual data values. It might looks something like:

```
{
    "id": "978-0-1234-5678-X",
    "title": "Moby Dick",
    "authors": [ "Herman Melville" ],
    "language": "en-US",
    "pubDate": "1851-10-18",
    "publisher": "Mark Twain Press",
    "coverImage": "https://example.com/images/mobidick_cover.jpg",
    // etc.
},
```

Each of the above is a data field in a database somewhere. Now, because I know I need it, I have language and direction information for each of the textual fields also in my database. I even have stuff like a pronunciation field for title and author (for sorting Chinese and Japanese). Those are just data fields. Do I really want to serialize them as HTML:

```
   "title": "<span lang='en-US' dir='ltr'>Mobi Dick</span>"
```

After all, I may not end up displaying the `title` field in an HTML context! My JSON might very well be used to populate say the device local data store which uses native controls to show the title.

I'd also argue that:

> a good bit of extra overhead for developers in the common case where they're not going to be interested in adding language or direction information

... is probably wrong. The common case where you don't want language or direction information is for non-language-bearing fields (`isbn`). Omitting the information for language-bearing fields is basically an I18N bug (yeah, being a pedant here)

**Comment by dwsinger** [comment]
Not to be a pedant, but if you separate the language tag from the other fields, don't you introduce ambiguity or risk of error?

{
    "id": "978-0-1234-5678-X",
    "title": "Quo Vadis",
    "authors": [ " Henryk Sienkiewicz" ],
    "language": "la",
    "pubDate": "1895-10-18",
      // etc.
},

The title is indeed in Latin. The book was originally written in Polish. But maybe this edition is in some other language. This becomes particularly problematic if two fields need different tagging (here, the author's name might be tagged as "pl" -- Polish).

**Comment by aphillips** [comment]
@dswinger Exactly so. The book language(s) (the language(s) of the intended audience) might be (often are) different from the language of the title or the author. The `language` field really _is_ wrongly ambiguous, given that each field (title, author, publisher name) needs language and direction metadata.

**Comment by hsivonen** [comment]
Solution 1 that would require changes to JSON itself isn't practical, because it would be too much of ocean boiling effort to change all JSON parsers.

I think Solution 2 potentially with bidi control characters within string values is workable.

> This seems related to the discussion currently happening in heycam/webidl#358, where we're attempting to add a shared primitive to Web IDL that all specs can use, and getting stuck. The point of contention is basically whether the pattern should be
> 
> ```
> someAPI({
>  lang: "...",
>  dir: "...",
>  label: "a string governed by the lang/dir"
>  name: "another string, governed by the same lang/dir"
> });
>```
> (the "`Localizable` base dictionary" solution)
>
> or
>
> ```
> someAPI({
>  label: {
>    lang: "...",
>    dir: "...",
>    value: "a string governed by the lang/dir"
>  },
>  name: "another string, using the default lang/dir"
> });
> ```
> (the "`LocalizableString union` typedef" solution).
>
> The former makes it easier to say that all strings have the same lang/dir. The latter allows more granular decision making, at the cost of verbosity.

I would expect the former to face less resistance, because it just adds some key-value pairs without forcing a reorganization of a given JSON-based format compared to its lang/dir-unaware version. Moreover, considering JSON from the perspective of developers trying to escape XML, the added nesting/complexity of the latter would probably not be well received. Therefore, I think pushing the latter as the only option wouldn't be productive.

A third option would be:

```
someAPI({
  label_lang: "...",
  label_dir: "...",
  label: "a string governed by label_lang/label_dir",
  name_lang: "...",
  name_dir: "...",
  name: "another string, governed by name_lang/name_dir"
});
```

> whether we should be encouraging the use of HTML rather than text

I think using HTML in JSON makes sense for strings that carry multi-paragraph text with inline formatting (i.e. something that would make sense inside HTML `<body>`), but I think it wouldn't be good to recommend markup inside JSON for strings that are closer to HTML `<title>`, email subject line, name of a person, a GUI label, invoice/inventory line item, etc.

Even though HTML parsers are now widely available, a plain-text string is a significantly simpler thing for the consumer's _data model_ to deal with than a tree rooted at DOM `DocumentFragment` or equivalent in a non-DOM markup tree API.

People use JSON instead of XML to avoid various complexities of XML and to use a format that maps nicely to and from basic programming language data structures. Making shortish plainish strings (not just ones representing multi-paragraph text with inline formatting) in JSON potentially carry markup would defeat both avoiding XML mixed content complexity and having a format that maps nicely to and from basic programming language data structures.

When a JSON-based format wouldn't use markup in strings for non-bidi reasons, to the extent a base direction taken from an adjacent key-value pair isn't enough, I think finer-grained bidi control should use the bidi control characters instead of importing the full _data model_ complexity of markup for every (human-readable) string.

(Whereas bidi is intrinsic to whole scripts, ruby is a sometimes-used (relatively rarely-used even) typographical device for the scripts with which it is used, so I think it cases where bidi doesn't justify the complexity of markup, ruby doesn't, either.)

**Comment by travisleithead** [comment]
A lot of great points have been made in this thread. I'm personally not convinced that there is any single "right" solution. 

It seems that if we want to create a compact data representation for strings, associating lang, direction, and other meta-data about the string, then this encoding has to be as maximally-portable across systems as possible, which leads me to think it must be some new representation of a string literal. That of course, is asking for a huge change across all programming environments and applications--not likely to happen, but neat to dream about--or even start some activity there, perhaps in Unicode.

For a serialization memory layout that associates lang, direction, etc., metadata about strings, I don't offer a strong opinion, though I have a weak opinion: keep it simple, or it will likely be too much of a burden to get much traction. For example, I think a simple dictionary with fields at parallel depths would work fine for most applications, e.g., { lang: .., dir: .., stringvalue: ... }.

**Comment by aphillips** [comment]
@travisleithead I tend to agree. It would have been nice to address this in the past, but we're here now.

However, building recommended patterns and best practices would allow specs to be consistent and interoperate well.

**Comment by r12a** [comment]
> The common case where you don't want language or direction information is for non-language-bearing fields (isbn).

Watch out though, apparently harmless data may not actually be so. The isbn field will only display correctly if it is _isolated_ when displayed in a RTL target context and treated as LTR inside that isolated area. For example, if i just drop the text into a field on a RTL page without any precautions, i get:

![screen shot 2017-07-17 at 18 11 08](https://user-images.githubusercontent.com/4839211/28280380-7a91fdcc-6b1b-11e7-8dc9-341d77ad51d3.png)

rather than what i really want, which is:

![screen shot 2017-07-17 at 18 11 19](https://user-images.githubusercontent.com/4839211/28280391-81235b68-6b1b-11e7-9ab8-2a073370593a.png)

However, if the value were a range, such as 100-300, the first arrangement would actually be what's wanted in Arabic (though not Hebrew, and i'm not sure about N'Ko), otherwise the range would appear to be decreasing instead of increasing.

So it may actually be useful to have some direction information for isbn numbers, MAC addresses, telephone numbers, etc.

**Comment by dbaron** [comment]
Though in those cases there's a tradeoff between having the direction data in the text data, versus having the application have knowledge of the correct way to present the particular field, since there is a correct and simple per-field algorithm (although it's not particularly simple to have tens or hundreds of them).  One is easier for the producer of the data and the other is easier for the consumer.

This is different from cases where you basically have to have the direction data stored in the text because you can't trivially derive it from the text.

**Comment by r12a** [comment]
Please be advised that i18n WG is now documenting the issues and probing some solutions at https://w3c.github.io/string-meta/

This gathers and refines information from 3 earlier documents listed at https://w3c.github.io/string-meta/#Acknowledgements

**Comment by torgo** [comment]
Scheduled for 15:00 hopefully with @aphillips and @r12a.

**Comment by torgo** [comment]
Suggestion to reference webapp manifest as a specific use case https://github.com/w3c/manifest

**Comment by dbaron** [comment]
We discussed this for nearly an hour today.  Some next steps:
```
15:57:56 <r12a> 3 actions for i18n:
15:58:08 <r12a> 1. provide usage scenarios and example to understand issue
15:58:23 <r12a> 2. provide pointers to wgs that have expereienced problems
15:58:42 <r12a> 3. explain how unicode language tags actually work - you won't like it
15:58:47 <r12a> action for tag
15:59:12 <r12a> 1. send i18n descriptions of things you don't think will work, and why
```

**Comment by tobie** [comment]
Happy to join the next TAG conversation on this topic for the WebIDL bits.

**Comment by r12a** [comment]
i18n action 3 above is now done at https://w3c.github.io/string-meta/#unicodeTags

**Comment by r12a** [comment]
i18n action 1 above is now available at 
https://w3c.github.io/i18n-drafts/articles/strings-and-bidi/index.en

I had been wanting to create this set of examples for many months, not just for this thread, so i created a standalone article for it. It's currently out for wide review.

**Comment by r12a** [comment]
I have added a third potential solution at the end, which uses language information to guess at direction.  Please take a look and send any comments you have.

http://w3c.github.io/i18n-drafts/articles/strings-and-bidi/index.en.html#third

**Comment by dbaron** [comment]
So (to try to fulfill the TAG action from https://github.com/w3ctag/design-reviews/issues/178#issuecomment-317771124) here's an attempt to write the list of things that won't work:

1. **adding new string syntax to JSON.**  JSON is a widely deployed format with a large number of implementations.  Adding new syntax to strings in JSON would not work in many of these implementations, and would thus lose many of the advantages of using JSON in the first place.  (I'd give one caveat, though:  if we limit the conversation to Web APIs that use WebIDL dictionaries, I think we have a bit more flexibility, since dictionaries can have members that are JS objects but not valid JSON.  So a solution that was limited to Javascript and not JSON could have something *like* what you propose, although done using new types with constructors rather than new low-level syntax.)

I'd also add a list of things that have serious potential risks/downsides, although not necessarily ones that completely rule out these options:

2. **optionally being able to replace strings with JSON objects.**  If we add the ability to write either `name: "David"` or to write `name: { string: "David", lang: "en", dir: "ltr" }` then I see two risks:
    a. Implementations will end up supporting this syntax in only some of the places where it's supposed to be allowed, since most testing will end up not testing this variant, and then developers will be frustrated when it doesn't work.
    b. Developers will use this syntax in places where it isn't formally allowed by the spec, leading to the same frustration.
In these cases, not working will mean the string being dropped (or maybe replaced with `[object Object]` or similar), since the implementation was looking for a string but found an object, so the failure mode is pretty bad.  If we were to use this option, I'd want to see a clear strategy for how we get the platform as a whole into a consistent state in the long term.

3. **requiring that strings be replaced with JSON objects.**  This is like the previous option, but requires the additional object.  Removing the ability to write `name: "David"` from the previous version reduces the risk of (a), but increases the risk of (b), and also probably increases developer frustration from developers who think they don't need to care about this (which may or may not be true).  It probably also increases the cost of inconsistency within the platform.

4. **being able to add lang/dir properties to objects that contain strings.**  Going instead with the solution that adds lang and dir as siblings of the string, potentially applying to multiple strings (e.g., `{ name: "David", role: "TAG Member", lang: "en", dir: "ltr" }`) does address the issues with the previous two options, but instead makes it harder to work with the underlying data.   This option would mean that copying the name property elsewhere (e.g., to a different object) loses information that was supposed to be associated with the name property, unless substantial care is taken.  And since it's not even clear how to resolve conflicts (e.g., to take the name from `{name: "Sangwhan", lang: "ko" }` and the role from `{role: "TAG Member", lang: "en" }` and put them on the same object), I suspect many developers wouldn't even try to do better since there fundamentally isn't a good way to do it.

I'm sure I've forgotten something I meant to include, though...

**Comment by dwsinger** [comment]
Two minor comments. (a) this is a general problem in programming languages, I think. (b) logically, we could also think of a syntax within the string itself. There, two possibilities come to mind.
i) 'visible' syntax, such as HTML-like. "<span lang=\"en-us\">text in multiple languages</span>"
ii) invisible syntax, i.e. escape sequences at the character level (anyone remember VT100 escape codes)? (Please don't barf, it's a logical possibility that I think we'd all abhor).

**Comment by dbaron** [comment]
Regarding (ii), invisible escape sequences within the string itself are pretty similar to using Unicode codepoints that do these things.  They have the advantage that they can be copied around between more formats, but the disadvantage that they're invisible metadata and thus tend to get out of sync with the data (e.g., when copied unintentionally), and also being quite hard to edit without something like a hex editor.

I think if we wanted something within the string itself, I'd be in favor of it being visible rather than invisible.

But https://github.com/w3ctag/design-reviews/issues/178#issuecomment-313783678 argues against that sort of solution, as does the issue of such data being harder to consume.

**Comment by dbaron** [comment]
Discussed in today's TAG meeting a bit; we'll take it to an extra time breakout discussion today or tomorrow.

**Comment by dbaron** [comment]
@cynthia and I just had a breakout discussion of this.

I think one conclusion that we came to is that the option of having a lang that applies to multiple strings is a little weird, e.g., in:
```json
{
  "title": "Nice",
  "description": "Une ville française",
  "lang": "fr",
  "postcode": "06000"
}
```
it feels weird that the `"lang"` applies to both the `"title"` and the `"description"` but not the `"postcode"`.  That just doesn't feel to me like the way JSON works.  In other words, I think we lean towards the solutions that have the language information of the `"title"` to be inside the value of `"title"`.

So then given the options that we've talked about so far, I think that only leaves two options, one of which is to say that we'd require what I'll call (A):
```json
{
  "title": { "text": "Nice", "lang": "fr" },
  "description":  { "text": "Une ville française", "lang": "fr" },
  "postcode": "06000"
}
```
where only the `"text"` property would be mandatory, i.e., where you could write this (B):
```json
{
  "title": { "text": "Nice" },
  "description":  { "text": "Une ville française" },
  "postcode": "06000"
}
```
if you didn't have language information, but that would forbid (C):
```json
{
  "title": "Nice",
  "description": "Une ville française",
  "postcode": "06000"
}
```

The alternative remaining option would instead allow (C) as an equivalent to (B).

-----

@cynthia also brought up the issue of how this extends to when you have text in multiple languages.  For example:
```json
{
    "name": [ {"lang": "fr", "text": "Nice"}, {"lang": "ja", "text": "ニース"} ]
}
```
or perhaps more JSON-ish:
```json
{
    "name": { "fr": {"text": "Nice"}, "ja": { "text": "ニース"} }
}
```
although the latter doesn't allow the specific strings to be passed around without creating a new object.  But the former has slow search.

Here you'd now have to test whether the value of `"name"` is an object or an array (are those the right JSON terms?).  In theory the alternative could be to force a list, but that feels like we're going down a very different use case.

-----

So another question for the folks who raised this issue is that it might help us to have a better idea of what the range of use cases where this comes up looks like.  Are there a few representative examples we can look at to make this a little more concrete?

**Comment by annevk** [comment]
FWIW, Notifications API has something like this: https://notifications.spec.whatwg.org/#api. There `lang` and `dir` span both `title` and `body` though. This is similar to how in HTML the `lang` attribute also applies to the `title` or `alt` attribute, along with the contents of the element.

**Comment by cynthia** [comment]
Right, so that design is probably close to (but is a lot more complete than) one of the proposals above - but in a multilingual payload context we still have the lookup problem described above. I don't have any particularly good ideas on how to tackle this without a better manifest of the use cases though...

**Comment by tobie** [comment]
> The alternative remaining option would instead allow (C) as an equivalent to (B).

This is conceptually very similar to the [LocalizableString proposal](https://s3.amazonaws.com/pr-preview/marcoscaceres/webidl/localizable.html#localizable) we discussed in https://github.com/heycam/webidl/pull/358.

**Comment by r12a** [comment]
Having the `lang`/`dir` values span both `title` and `description` is problematic, not because it doesn't cover postcode, but because the title and description may be in different languages.  This is why we have also long wished there was an alternative to having one `lang` attribute in HTML to cover both the element content and the attribute values (and why, more generally, we advise avoiding natural language text in attribute values when designing markup languages).

Having said that, markup like HTML can be useful in that the content author doesn't need to specify the language for every element – the language is inherited from higher up the hierarchy. This is not so easy for JSON-like formats, but would be useful if it's possible.  For example, it may be possible to declare the language for all the strings in A in the way you did, but this would only work if it were possible to override that for a particular string when needed.

**Comment by tobie** [comment]
@r12a see: https://github.com/heycam/webidl/pull/358#issuecomment-300105542.

**Comment by dbaron** [comment]
We discussed this briefly today in the TAG's teleconference, and were wondering if we could find a way (and time) to make progress on this at TPAC.  @cynthia is sending email about this, but noting this in github as well.  /cc @r12a @aphillips

**Comment by aphillips** [comment]
@dbaron Happy to coordinate a time.

**Comment by dbaron** [comment]
[Discussed in i18n today](https://www.w3.org/2017/11/07-i18n-minutes.html).

**Comment by dbaron** [comment]
And, for the record here, that discussion was reasonably productive and I think (if I'm recalling correctly) focused on two things:
* an object that can be used where a string would be used, but also carries language and direction information, such as `{text: "Moby Dick", lang: "en", dir: "rtl" }` (could use `text` or `value` or other things there)
* the ability to set defaults within a JSON object perhaps with `lang` and `dir` or perhaps with something like `default_lang` and `default_dir` (or should that be camelCase?), though this has both advantages (compactness) and disadvantages (need to augment the objects to readd the defaults in order to pass them around)

There was then further discussion about how to use the former in contexts where multiple languages needed to be provided (i.e., ability to use array or dictionary, where the dictionary has redundancy but may allow faster lookup assuming appropriate use of BCP49 language codes).  The redundancy is, however, preferably to having objects that can't be passed around because the language from the dictionary key needs to be added back on.

There was also a bit of discussion about JSON vs. WebIDL that I've forgotten.

The next step was that @aphillips was going to revise [the string-meta document](https://w3c.github.io/string-meta/) along these lines and then post it for review from those of us present (and others, if interested).  So leaving the `pending-external-feedback` label.

**Comment by aphillips** [comment]
Thanks @dbaron. The edits in question are in progress and I have an [action item](https://www.w3.org/International/track/actions/680) to notify this issue when complete. If you look at the String-Meta document, you can see the edits in progress (including recent commits today), although I have not yet reached closure enough to notify.

**Comment by cynthia** [comment]
@aphillips is there anything for us to follow-up on related to this?

**Comment by dbaron** [comment]
@aphillips We (the TAG) have a face-to-face meeting next week; curious if we'll have something to review by then.

**Comment by aphillips** [comment]
@dbaron @cynthia We're working on updating our [String-Meta](https://w3c.github.io/string-meta/) doc. Most of the changes we discussed have been implemented in a not-quite clean way (syntax in examples is not right yet). Super open to comments. Our next teleconference is Thursday, wherein our WG will discuss.

**Comment by r12a** [comment]
@dbaron I recently added a section about use of script subtags for guessing bidi info.  In addition to that, we noticed that some people were reading this document and not catching some of the key messages, so i have a plan to summary and simplify the text which is currently in progress, and waiting for some time to become available so that i can complete it.  That might be a good time for review (?)

**Comment by kenchris** [comment]
Related: https://github.com/w3c/manifest/issues/676

**Comment by aphillips** [comment]
@torgo Thanks. Would you like to invite my/Richard's participation? We can have an updated version of our doc ready, if the date is 2019-02-05. Is that the target date?

**Comment by cynthia** [comment]
I believe we discussed this in a previous call and was happy to close it off; and follow up on the issues in the group's tracker. I'll close this for now; thanks a lot for the long discussion and we hope to hear more from i18n in the future.

(Please re-open if I got the summary of our last discussion wrong).
