### ISSUE TITLE
Review Request for OpenType Variable Fonts Additions to CSS Fonts Module Level 4

### ISSUE THREAD

**Issue by drott** [w3ctag/design-reviews#183]
Hello TAG!

I'm requesting a TAG review of:

  - Name: OpenType Variable Fonts Additions to CSS Fonts Module, Level 4, specifically "font-variation-settings", the range property extensions to the font-style, font-stretch and font-weight additions to the @font-face descriptor, as well as the updated font-matching algorithm, section 5.2
  - Specification URL: https://drafts.csswg.org/css-fonts-4/
  - Explainer, Requirements Doc, or Example code: https://medium.com/@tiro/https-medium-com-tiro-introducing-opentype-variable-fonts-12ba6cd2369
  - Primary contacts: @drott

You should also know that...

The edits for font-variation-settings are analogous to font-feature-setings, and the range definitions as part of @font-faces are somewhat natural extensions over the CSS Fonts Level 3 specification. Similarly, the font matching algorithm extends the discrete algorithm of level 3 to supporting ranges for OpenType variable fonts. The OpenType variable fonts have been introduced as a joint industry effort by Apple, Microsoft, Adobe and Google. 

We'd prefer the TAG provide feedback as:

  - [x] open a single issue in our Github repo for the entire review

**Comment by dbaron** [comment]
So a few thoughts:

* this is yet another property that really would work a lot better if CSS had an option for additive cascading (appending to the list rather than replacing the overridden value)
* `font-feature-settings` shouldn't really be seen as a good model to follow; it's a property that doesn't work well within CSS's design (though introducing additive cascading would help), and the recommended way to use the majority of the features exposed by `font-feature-settings` is via the `font-variant-*` properties.  That said, I don't see a better solution here, although I wonder if the spec should also explicitly point to `font-weight`, `font-stretch`, etc.  I also wonder whether those properties should become continuous rather than discrete.  (I think there was some discussion in the working group of making at least `font-weight` continuous.)

**Comment by dbaron** [comment]
Oh, one other question:
* should this be a property, a descriptor, or both?  It seems a little bit odd to specify it as a property, which means that it applies to whatever font happens to be chosen, when it seems somewhat likely that the declaration was really for a specific font.  Then again, a declaration could usefully apply across a font family... but on the other hand, could still lead to bad results if font download is disabled to save bandwidth, particularly as more system fallback fonts are themselves variable fonts.

**Comment by dbaron** [comment]
@travisleithead, @plinss, @hadleybeeman, and I just discussed this a bit at the TAG meeting.  I think we were all inclined to agree with the idea (per w3c/csswg-drafts#1652) that a descriptor feels better than a property because of fallback.  Though @plinss brought up the issue of animation, but I wasn't really sure how important a use case animation really is.  (Perhaps it becomes more valuable to animate things like `font-weight` now that they can be animated with fidelity, though.)

Otherwise I don't think we have any other feedback.

**Comment by svgeesus** [comment]
Now that 
a) font-weight is an actual continuously-variable number in the 1 to 999 range (per OpenType spec, although unlike CSS3 Fonts and earlier, where it was an enumeration of number-like strings: "100" "200" etc
b) Variable fonts are intended to cover a range of variations and be instantiated on-the-fly, on-demand (rather than choosing from one of a fixed set of instantiations)
then animating fonts is much more of a reasonable use case than previously. Discussing this with people close to the font industry (particularly Erik van Blokland, but also Roel Nieskens and others) animation with variable fonts is a strong request.
