### ISSUE TITLE
Review request for IndexedDB Observers

### ISSUE THREAD

**Issue by dmurph** [w3ctag/design-reviews#189]
Hello TAG!

I'm requesting a TAG review of:

  - Name: **IndexedDB Observers**
  - Specification URL: Nothing formal, but [here is an informal description of the changes that could happen in the IDB spec](https://github.com/WICG/indexed-db-observers/blob/gh-pages/SPEC_CHANGES.md).
  - Explainer, Requirements Doc, or Example code: **https://github.com/WICG/indexed-db-observers**
  - Primary contacts: **dmurph**

Further details (optional):

  - Relevant time constraints or deadlines: **Review within the next couple months would be nice.**
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). **The [assessment is here](https://github.com/WICG/indexed-db-observers/blob/gh-pages/tag-security-privacy-doc.md).**
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

**Chrome has a working implementation that is a little older than the current design (some of the options are different, the IDL is a little different). But the functionality is the same. Currently still unimplemented in Chrome: Object store key range filtering.**

**I've been addressing issues from many people already, please file issues [in the github issue tracker for the project here](https://github.com/WICG/indexed-db-observers/issues).  I'm excited to hear your feedback! :)**

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

--------------------------

_Please preview the issue and check that the links work before submitting_

For background, some decent explainers:

  https://github.com/w3c/ServiceWorker/blob/master/explainer.md
  https://github.com/zkoch/paymentrequest/blob/gh-pages/docs/explainer.md
  https://github.com/WICG/IntersectionObserver/blob/gh-pages/explainer.md (although this one includes IDL, which an explainer should not)

**Comment by travisleithead** [comment]
Thanks for raising this issue; we are super (happy that this has a great explainer and other ancillary documents that flesh out the idea in great detail (so often these important points of background are omitted)!

A bit of initial feedback:
* We noticed in the "Why?" section of the explainer that the points made were all rather clinical and focused on the scenarios the feature enables; however we felt that a few notes about the problem space that motivated the feature would be in order (from the web dev perspective). For example: Many web developers often update a database in a worker (or somewhere separate from the UI) and must write a custom notification system (or polling) in order to know when the database was updated from the UI context. Something like that :-)
* You have a current design illustrated; what alternatives were considered? Would be great to note that in the explainer.
* This feature is strongly tied to IndexedDB, but it seems that the same problem exists for other classes of storage (like local/session storage). We would love to see this expanded and somewhat generalized to handled these additional storage scenarios. E.g. "IndexedDBObserver" => "StorageObserver" :-)

Once again, we were totally blown away with the quality of the examples in your doc. Would that all design reviews were this excellent. We're grateful you reached out to the TAG, and hope we can continue to be of service. Thanks!

**Comment by travisleithead** [comment]
@slightlyoff and I were thinking about how cookie storage might even be included as a storage category (e.g., for a potential "StorageObserver"), and found https://github.com/WICG/async-cookies-api/blob/gh-pages/explainer.md. Wonder if that proposal has a comparable model, what might be learned from it, and thoughts on how it might it related/integrated?

**Comment by bsittler** [comment]
I think the semantics and use cases are different enough that sharing a single event type for cookies and IDB would introduce a lot of complexity for relatively little gain; however, following a similar pattern to the proposed InstallEvent .registerCookieChangeInterest + cookiechangeevent might make sense for IDB, e.g. InstallEvent .registerIndexedDBChangeInterest + indexeddbchangeevent with registration-time interest expression analogous to those used during observer registration (though perhaps only a subset, since unlike cookies there is not a conveniently small maximum size for the reported changes and having to keep a very large buffer of operations/transactions in memory until the worker is ready to handle the event could be very bad for performance) and reported changes in the handler analogous to those reported to an IndexedDB observer.

I also think the IndexedDB and cookie uses and storage models are fairly different, including for example:

- transactional vs. non-transactional,
- explicit-key vs. tripartite partially-hidden key,
- origin-scoped and always visible vs. domain-scoped+path-scoped+name w/conditional visibility based on "secure" flag + some always-invisible-to-script "httponly" entries that nevertheless have script-observable side effects,
- persistent-until-deleted vs. persistent-until-expired-or-end-of-session,
- script-only storage vs. client ⇆ server shared storage/messaging/authentication with only a subset useful to script,
- same-origin vs. used in cross-origin federation,
- very small maximum size vs. potentially very large values, and
- cookie partial eviction model vs. IndexedDB storage full model

**Comment by travisleithead** [comment]
@bsittler Thanks for your comments. After further discussion, we agree that cookies are probably not a great fit.

We did ask about integrating localStorage/sessionStorage (and potentially WebSQL for those who implement it). We noticed you didn't mention this storage type in your response above, and just want to make sure you considered them as well--they do seem much more aligned with Indexed DB than cookies ;-)

**Comment by dmurph** [comment]
I think that is interesting too. There are definitely going to be similarities if an observer was created for LocalStorage/SessionStorage/IndexedDB, but I'm unsure if the different background states / operational aspects are going to confuse developers, so this is actually a great question for you all!

Here is what would be the same:
* The observer construction (w/ calback)
* a .observe call, with options (note - options would now vary depending on storage system observing)

Differences:
* some observation options
  * indexeddb has some very specific options to facilitate complex use cases, like including a transaction, that don't really apply to localStorage, and localStorage / sessionStorage might want batching options that don't work with IndexedDB.
  * Other options like excludeValues would be fine for both.
* Consistency during change callback
  * IndexedDB Observers guarantees, with the transaction, that you can read in a consistent state where no new changes have been applied.
  * LocalStorage / sessionStorage doesn't have this idea explicitly, and I'm not sure what complications might arise here. If we're doing everything on one thread, then I guess we can't receive changes during our callback execution... @mek for whether this would be easy, or whether this is how it would work today anyways
* Intent behind group of changes
  * IndexedDB groups changes by transaction, exactly mirroring how the changes are applied by the developer. Very 1:1 easy reasoning about the changes, and allows data consistency guarantees.
  * LocalStorage and SessionStorage would probably group changes in batches (similar to cookie observer) where it waits for groups of changes, has some sort of max time / max operations, etc.
* Storage state in between change calls
  * IndexedDB is explicitly transaction-based in the changes, so before a transaction commits, those changes are not visible anywhere. The observer gets called right away when the transaction commits, and can react accordingly.
  * Local/session Storage would probably do batching for the observer, and thus the storage state could be changing before the observer is actually called. Not a bug or anything, just different.


Other things to think about:
- We already have events for local storage changes - but there is no batching here, so observers could improve performance for high-frequency changes.
- Do we want local storage observer support for ServiceWorkers? If so, we might want to go the route of cookies - although the implementation / api would probably be much simpler because it's origin scoped and not crazy-magic-scoped. Another question about whether sessionStorage is a thing for serviceworkers

So questions:
- Is the system state / storage system operation differences worth it to unify the observer object?
- Would it be weird to have different options for different calls to the .observe method?
- Do we want it to be possible to have the same callback be called for localStorage and IndexedDB changes?
- How would the changes dictionary support holding information for different storage systems, especially for specializations like IDB's transaction option?

My vote would be to either create separate observer object but keep the same pattern, or if we want to support batched observation of localStorage/sessionStorage on ServiceWorkers then we would need to explore an event-based solution.

**Comment by travisleithead** [comment]
@dmurph Thanks for the very thoughtful response; we appreciate giving this idea some consideration. You raised some great points which we discussed in brief in today's call:

> So questions:
>   Is the system state / storage system operation differences worth it to unify the observer object?

Possibly, but given your third point, we don't tend to think that use-cases would cause code patterns to be the same across these storage types...

> Would it be weird to have different options for different calls to the .observe method?

It might be a little weird, though MutationObservers have options that only apply to certain types of mutations (e.g., the `attributeOldValue`, `characterDataOldValue`, and `attributeFilter` are all pretty specialized). So this point doesn't sway us one way or the other.

> Do we want it to be possible to have the same callback be called for localStorage and IndexedDB changes?

This is where it start to seem apparent that unifying these two storage types may not make the best sense--it's hard to imagine common scenarios using one callback to handle both IndexedDB and localStorage in one shot. Primarily for this reason, we think that a unified approach may not be the best fit.

> How would the changes dictionary support holding information for different storage systems, especially for specializations like IDB's transaction option?

Great question.. ?

We filed a follow-up issue on our repo to track this (#210). Otherwise, thank you for requesting a TAG review, we hope we've been helpful.
