### ISSUE TITLE
CSS Selectors 4

### ISSUE THREAD

**Issue by victoriasu** [w3ctag/design-reviews#219]
Hello TAG!

I'm requesting a TAG review of:

  - Name: CSS Selectors 4
  - Specification URL: https://drafts.csswg.org/selectors-4/
  - Explainer, Requirements Doc, or Example code: N/A
  - Tests: https://github.com/w3c/web-platform-tests/tree/master/css/selectors (will be placed here)
  - Primary contacts: victoriasu, ewilligers (Blink implementation)

We'd prefer the TAG provide feedback as (please select one):

  - [x] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by annevk** [comment]
If you're implementing this, how are you dealing with all the currently open issues? Is there a plan to get them resolved?

**Comment by victoriasu** [comment]
Currently I am planning on firstly implementing :any-link, :has(), and :matches(). This would be progress in unblocking Issues 1 and 22.

**Comment by SelenIT** [comment]
@victoriasu are you planning to implement `:has()` for the Live selector profile (so Issue 1 could be resolved)?

**Comment by victoriasu** [comment]
@SelenIT I'm no longer planning on implementing `:has()` but I am currently implementing `:matches()`

**Comment by SelenIT** [comment]
@victoriasu, thank you!

**Comment by torgo** [comment]
Taken up at [London F2F](https://github.com/w3ctag/meetings/tree/gh-pages/2018/01-london). We noted that the lack of an explainer is problematic. Are the use cases documented?

**Comment by dbaron** [comment]
Also /cc @tabatkins @fantasai .

In addition to an explainer, it would probably also be useful to have a section that says what's new in selectors 4 relative to selectors 3.

**Comment by fantasai** [comment]
The levels for each selector are annotated in https://drafts.csswg.org/selectors-4/#overview

**Comment by slightlyoff** [comment]
Stream of consciousness reading the spec:

 * The [Overview Section](https://drafts.csswg.org/selectors-4/#overview) is slightly misleading regarding selectors that accept [Selector Lists](https://drafts.csswg.org/selectors-4/#grouping). E.g., instead of `E:not(s1, s2)`, consider `E:not(s1, s2, ...)`
 * `:something` (specificity adjustment) seems useful, but perhaps under-powered. Has the WG considered a modifier which would enable dropping the specificity of the left-hand side of a selector as well?
 * It seems there are quite a few missing examples in the text, and some examples don't discuss the Level 4 syntax (e.g., `:not()`).
 * It'd be great if there was a companion doc that detailed the motivations for these additions. What problems are they solving? How do we know that those problems are important? What design alternatives were considered and why were these versions chosen? This tends to be what's in an "[Explainer](https://docs.google.com/document/d/1cJs7GkdQolqOHns9k6v1UjCUb_LqTFVjZM-kc3TbNGI/edit)" (along with sample code that shows how the solution addresses the stated problems).
 * It's rather unfortunate to see input element state bleeding into everything. The new input-related pseudos seem like they could be perhaps subsumed by [`::part`](https://meowni.ca/posts/part-theme-explainer/) or an extension to that (/cc @notwaldorf)
 * The `||` (column) combinator reads to this programmer like "OR" 😞 

Overall this looks well done, and I'm glad to see there aren't many new descendant selectors (modulo the grid structural selectors).

**Comment by fantasai** [comment]
@slightlyoff Responses:
  * Added ellipses as requested.
  * `:something()` can be added to shield part or all of any compound selector, not just the last one. There were some comments on whether to e.g. use bare parentheses to allow any part of the selector to be eliminated from the specificity count without affecting the structure of the selector, see https://github.com/w3c/csswg-drafts/issues/2143#issuecomment-358124504, but there wasn't much traction. If you think this is an alternative worth pursuing, please comment to that effect in the bug and/or file a new one? (I think the parsing issue in Tab's reply is solveable by having two forms, `:()` within a compound selector and `()` for higher-level annotation.)
  * Filed https://github.com/w3c/csswg-drafts/issues/2267
  * Tab and I believe that content that explains a feature belongs in the spec, not a separate document; in other words that the spec should be written understandable on its own, without auxiliary information, both to implementers and to authors. If there is insufficient context to understand the feature in the spec, then the spec should be improved (e.g. by adding examples, as you requested above). If you would like an archaeological record of the decisions made so that you can analyze whether they were good decisions or not, please let me know how detailed you want them and I will set aside the necessary time. A quick overview from memory should take a day or so. A disposition of comments since 2011 will probably take weeks.
* `::part` is for styling _parts_ of an input control, that is why it's a pseudo-element. The Input Pseudo-classes are for selecting _state_ of an input control, which is why they're pseudo-classes. In any case, these are quite old (they first appeared in the CSS UI draft ~2002, were published as CR in 2004, and were moved to Selectors much later) and most have been implemented and deployed already.
  * Do you have a suggested alternative? :) If you feel strongly about it, file an issue for bikeshedding~ ^_^

**Comment by slightlyoff** [comment]
Sorry for the slow reply.

We discussed again today at the W3C TAG F2F in TOK. Happy to see this move forward.

 * Thanks!
 * @dbaron talked us through this one and we agree that a new syntactic form would be pretty difficult here. Any update on a potential name?
 * Thanks for filing. Any luck getting more examples in?
 * Regarding the place for explainer-style justification for features, I'm not dogmatic. That could be in a non-normative section of a spec, but it'd still need to include all the detail of motivations, considered alternatives, and enough explanatory code to make the case for these particular additions. I haven't seen a spec doc that includes all of that, but it'd work.
 * Thanks for explaining `::part` pseudo. Makes sense!
 * Don't have a suggested alternative and don't feel too strongly.

**Comment by LeaVerou** [comment]
> Any update on a potential name?

Last time we discussed this in the call we could not reach consensus on the name, and decided to discuss more in the Github issue that @fantasai linked to (https://github.com/w3c/csswg-drafts/issues/2143). Please weigh in if you have opinions!
