### ISSUE TITLE
Canvas TextMetrics

### ISSUE THREAD

**Issue by fserb** [w3ctag/design-reviews#302]
Bonjour TAG,

I'm requesting a TAG review of:

  - Name: new TextMetrics on Canvas
  - Specification URL: https://html.spec.whatwg.org/multipage/canvas.html#textmetrics
  - Explainer, Requirements Doc, or Example code: (this is an update of a current API. Can provide a demo if needed)
  - Tests: 2dcontext/drawing-text-to-the-canvas
  - Primary contacts: fserb

Further details (optional):

  - Relevant time constraints or deadlines: 
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). I've read but this change doesn't expose any new security or privacy vector.
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

A version of this API has already been implemented on Chrome/Firefox/Safari. We are asking for review over an updated version that also matches discussions had over the [CSS houdini spec](https://github.com/w3c/css-houdini-drafts/blob/master/font-metrics-api/Overview.bs) [discussion](https://discourse.wicg.io/t/font-metrics-api/2417). The hope is that, in the future, we could merge those two specs.

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify fserb

**Comment by dbaron** [comment]
Fundamentally these seem like reasonable things for `measureText` to return.

While I'm not sure feedback here is the best way to get issues back to the editors, a few comments/questions:
* how do `actualBoundingBoxLeft` and `actualBoundingBoxRight` deal with vertical text?  (Even if the answer is "this API doesn't currently support vertical text" (which seems to be the case since [CanvasTextDrawingStyles](https://html.spec.whatwg.org/multipage/canvas.html#canvastextdrawingstyles) has `direction` but not `writingMode`)... the names seem bad for when it's likely to be extended to do so in the future.)
* how do the definitions of "positive numbers" for all the `*Ascent` and `*Descent` values deal with vertical text?
* there are multiple references to a "line box", yet I don't see anything that says what this line box is.  Do these mean "inline box" instead?
* it seems like `hangingBaseline`, `alphabeticBaseline`, and `ideographicBaseline` should define the behavior when multiple fonts are present.  Is it the [first available font](https://drafts.csswg.org/css-fonts-4/#first-available-font) what should be used?
* the API methods don't say anything about what rounding is performed.  Is the expectation that the results be round numbers of CSS pixels, round numbers of device pixels, or unrounded?
* all of the "positive numbers indicating that the given baseline is (below/above) the X" seem confusing to me, and seem like they'd be clearer if they were swapped to "positive numbers indicating that X is (above/below) the given baseline" (note that the order is swapped and the above/below are swapped so that the statement is still true).  That's probably just preference, though.  (But it does make them more consistent with the preceding 4 definitions.)
* the definitions of `emHeightAscent` and `emHeightDescent` should probably have wording that repeats the "of all the fonts used to render the text" used in defining `fontBoundingBoxAscent` etc., assuming that is what is intended (which I think it is given the "highest top" and "lowest bottom" wording); otherwise it's not clear what it's the "highest" or "lowest" of.  (For example, it's important that it's all fonts used to render the actual text rather than all fonts that could have been used given any possible text.)
* the "half the font size if the given baseline is the middle of that em square" comment only seems true if there's only a single font or if the em squares of all fonts used line up (at least assuming my previous assumption was correct)

**Comment by kenchris** [comment]
@justinfagnani is using `createTreeWalker` in lit-html https://github.com/Polymer/lit-html/blob/14f7e67b1a325946030aff031d4518c4a9e54ff2/src/lib/template.ts#L53

**Comment by plinss** [comment]
At first glance it looks like some useful metrics are missing, specifically ex height and cap height (also mathematical baseline?).

My primary concern here is coordination with the Houdini Font Metrics API, first that I don't want to have multiple (and different) ways of getting font metric data, second that the Houdini Font Metrics API work seems to have stalled. One of the issues there was discovering that the problem was more complex than originally thought and a lack of relevant expertise.

We do need a good font metrics API for the platform and I'm glad to see this is getting worked on.

**Comment by dbaron** [comment]
Last week we left this open so that I could file issues against HTML for the feedback above; I was hoping to do that for this week, but didn't.

**Comment by dbaron** [comment]
I think what I reviewed was actually post-revert.  I'll file some issues, though.

**Comment by dbaron** [comment]
The 4 issues I filed above cover all of the points in my https://github.com/w3ctag/design-reviews/issues/302#issuecomment-422999075 .  Perhaps @plinss wants to file issues on his comment following it?

**Comment by dbaron** [comment]
We discussed briefly in today's TAG meeting -- given that (a) the spec changes got reverted and (b) I filed some feedback anyway, we don't think there needs to be more happening in this review right now.

That said, we're interested in:
* progress on the above filed issues against HTML
* future work related to re-making the original changes, Houdini work in this space, and the relation between them.

So if there is future work in that area, we'd be interested in seeing another review request... ideally pointing back to this one so we don't lose all the context (although hopefully we'd be able to find it ourselves).

Thanks for reaching out to the TAG for review.
