### ISSUE TITLE
Base used to resolve relative URIs to absolute URIs in HTML5 data-blocks

### ISSUE THREAD

**Issue by azaroth42** [w3ctag/design-reviews#312]
Salut le TAG,

I'm requesting a TAG review of:

  - Name: JSON-LD embedded in HTML with relative URIs
  - Specification URL: https://github.com/w3c/json-ld-syntax/issues/23 
  - Explainer, Requirements Doc, or Example code: https://gist.github.com/azaroth42/40fa22c0bb86c1fc92063fee5a7c3d4e
  - Tests: None (examples embedded in explainer could be used as tests though)
  - Primary contacts: @azaroth42 @bigbluehat @iherman @gkellogg

Further details (optional):

  - Relevant time constraints or deadlines: [please provide]
  - [ ] I have read and filled out the [Self-Review Questionnaire on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](url).
  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our Github repo for each point of feedback
  - [ ] open a single issue in our Github repo for the entire review
  - [X] leave review feedback as a comment in this issue and @-notify @azaroth42 @bigbluehat @iherman @gkellogg

Please read the explainer, as it summarizes the discussion for the issue. Discussed with Hadley on the Friday of TPAC.

Many thanks for your time.

**Comment by annevk** [comment]
A lot of the debate in that issue is about `xml:base`, which we dropped support for. Does that simplify your problem?

**Comment by iherman** [comment]
@annevk, as I commented in https://gist.github.com/azaroth42/40fa22c0bb86c1fc92063fee5a7c3d4e#gistcomment-2745279, `xml:base` should indeed be removed from the conversation, but it only marginally simplifies things. Due to the possible presence of the `<base>` element, the fundamental question remains.

**Comment by azaroth42** [comment]
Thanks @annevk. Unfortunately, if you look at the explainer, only 2/7 of the scenarios rely on `xml:base`, the others are around `base`, `link` and, at one step of separation, the`lang` attribute.

So ignoring `xml:base` does simplify the issue slightly, but not to the point that we're comfortable simply making a decision without further insight.

**Comment by annevk** [comment]
So conceptually there's only one base URL per document, the document's document base URL, as you've observed. Unfortunately it's mutable, due to the `base` element, but that's the only thing the `base` element changes here.

**Comment by iherman** [comment]
@annevk yes, indeed. So the question is, succinctly, whether it is acceptable for a JSON content in a datablock to ignore the effects of those mutations, and the value of the `base` element, and use only the document's URL when handling relative URL-s within the JSON content.

**Comment by iherman** [comment]
To add (to make it less succinct:-) whether the same freedom is allowed in terms of the language tag: is it o.k. to ignore the language that can be deduced for the enclosing `<script>` element. (There is no, alas!, equivalence to the `baseURL` on an HTML Element in the DOM for the language, so it is not exactly the same.)

**Comment by annevk** [comment]
I'd expect software to take into account `<base>` as it's global (and use script element's node document's document base URL). Language seems a little trickier and really depends on whether it makes sense to use the inherited language for a data block.

**Comment by hadleybeeman** [comment]
Hi JSON-LD! We discussed this at length at our [TAG Paris face-to-face](https://github.com/w3ctag/meetings/tree/gh-pages/2018/10-paris).  As I'd expected, it spawned a lot of good discussion about JSON-LD and its relationship to the rest of the web.

We had a number of thoughts:

1. We don't want JSON-LD documents, by definition, to need a DOM. [Data on the web](https://www.w3.org/TR/dwbp/), where intended to be machine-readable instead of human-readable, shouldn't have to jump through all those hoops – unless you're embedding JSON-LD into HTML. (Which is the use case you're highlighting here. So we'll focus on that.)

2. Where you are embedding it into HTML, JSON-LD is a valuable data store format for a lot of different use cases. We think it could be the default data format for the web – if it was exposed to the DOM (when embedded in HTML).
To that end, we would like to define a JavaScript API for those script elements, to reflect that content back out to DOM. 
Now that we have JavaScript modules... it would be useful to define the static export of a JSON-LD processor, for use as a module. @travisleithead has been working on an HTML modules proposal. We should make it possible to identify the module typing of all of our resource types: imaging, types, scripts, CSS, etc. -- and it would be ideal to include JSON-LD in that list, and treat it like we treat all of our other resources. We should bring this in from the cold; it's too important not to use with the rest of the Web.

3. The downside of this proposal is that it means we would all be treating JSON-LD like every other resource in the Web – which come with all the heavy lifting you've outlined in your [Detailed Design Discussion](https://gist.github.com/azaroth42/40fa22c0bb86c1fc92063fee5a7c3d4e#detailed-design-discussion) section of your explainer.
Sorry about that!!
If you're up for this, the next step would be to set up a call with me, @travisleithead and @slightlyoff to talk about how to take this forward. 

4.  To answer your question then – we would recommend that, where JSON-LD is embedded in HTML, we should treat it as part of the DOM (and it should be! A valuable part!) and resolve relative URIs to absolute URIs using the <base> element. 
Where JSON-LD is not embedded in HTML, and is therefore outside of a DOM – it makes sense to just use the document's URI to get to the absolute URI.

**Comment by hadleybeeman** [comment]
Also, and belatedly – thanks for the beautiful explainer, @azaroth42. Clear and well-explained; very helpful for our discussion!

**Comment by BigBlueHat** [comment]
Thank you for that summary @hadleybeeman!

To be clear(er?), there are two warring scenarios:
1. embedding JSON-LD into HTML for *conveyance*
2. embedding JSON-LD into HTML for *enhancement*

Currently, JSON-LD in a [data block](https://www.w3.org/TR/html5/semantics-scripting.html#data-block) is (like anything in a data block) simply there for conveyance. JavaScript *may* use it to inform the current page's interactions or it may not. Typically, because Schema.org, it's primarily there for SEO reasons.

The more futuristic hope/dream is that JSON-LD would become as @hadleybeeman described a more valuable part of constructing meaningful documents and apps whereby JSON-LD content might become deliberately intertwined with other data within the page.

These two scenarios currently look identical:
```html
<script type="application/ld+json">{"@contenxt": "..."}</script>
```
But the desired level of integration with the surrounding markup depends on which one of those scenarios one is currently focused on--as well as if the JSON-LD is seen as primarily existing on its own and occasionally embedded (for conveyance) into HTML or if the JSON-LD's whole purpose is to influence the surrounding documents processing/handling/scripting.

Both usage scenarios are valid, but if they go in the same data block space, there's concern about breaking existing tooling--[not all of which uses the DOM](https://github.com/w3c/json-ld-syntax/issues/23#issuecomment-430791254).

Hope that helps a bit!
🎩

**Comment by BigBlueHat** [comment]
>     3\. If you're up for this, the next step would be to set up a call with me, @travisleithead and @slightlyoff to talk about how to take this forward.

@hadleybeeman we'd like to have you @travisleithead and @slightlyoff join us for a future JSON-LD call. Our next available opening is December 14th (next Friday). If that's too soon for scheduling (because December), then we'd love to get something on the calendar for early next year.

We can schedule it here or via email if that's better. Thanks!

**Comment by torgo** [comment]
Discussed at Tokyo f2f and @hadleybeeman will reach out to @BigBlueHat to join one of their calls with some combination of @hober @slightlyoff @travisleithead.

**Comment by hadleybeeman** [comment]
@azaroth42, We're looking at this at our face-to-face in Tokyo, and would love to join you for a call.  (That's me, @hober and @slightlyoff). What is your schedule?

**Comment by BigBlueHat** [comment]
@hadleybeeman we're currently in the midst of our [Winter Face-to-Face](https://www.w3.org/2018/json-ld-wg/Meetings/F2F/2019.02.DC), but would love to get you scheduled for an upcoming call with the WG.

We meet every Friday at noon Eastern ([see other timezones](https://www.w3.org/2018/json-ld-wg/Meetings/#teleconferences)).

Please let me know what works for y'all and I'll get you added to the agenda!

Thanks!
🎩

**Comment by BigBlueHat** [comment]
@hober @slightlyoff @travisleithead @hadleybeeman do any of these three upcoming Friday's work for y'all?

* February 22
* March 1
* March 15

All of them are at noon Eastern ([see other timezones](https://www.w3.org/2018/json-ld-wg/Meetings/#teleconferences)). @azaroth42 and I will make sure you're on the calendar for whichever one of those works best for you collectively.

**Comment by hober** [comment]
@BigBlueHat Either of the March dates work for me.

**Comment by travisleithead** [comment]
Likewise.

**Comment by BigBlueHat** [comment]
Thanks @hober and @travisleithead! We just discussed the scheduling on the call, and *March 1* look best for the most participants. We'll get you scheduled for that date, and send reminders, etc.

Do you all have any minutes or other text we should read prior to that call?

**Comment by hober** [comment]
>Thanks @hober and @travisleithead! We just discussed the scheduling on the call, and *March 1* look best for the most participants. We'll get you scheduled for that date, and send reminders, etc. ...

@BigBlueHat hi, what are the call details?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by simonstey** [comment]
http://irc.w3.org/ #json-ld for irc

**Comment by azaroth42** [comment]
Can you see: https://lists.w3.org/Archives/Member/member-json-ld-wg/2018Jun/0000.html

**Comment by iherman** [comment]
I have also sent you a private mail with the same reference:-)

**Comment by BigBlueHat** [comment]
> @BigBlueHat hi, what are the call details?

Apologies for not CCing y'all on that! Thanks to all my fellow WG friends for providing the info. 😸

**Comment by hober** [comment]
Hi everybody,

On the call this morning we discussed the need for formats embedded in HTML to do base URL processing consistently, and the consensus on the call was to add language similar to the way CSS defines this in [§4.4.1 Relative URLs CSS Values Level 4](https://drafts.csswg.org/css-values-4/#relative-urls) "For CSS style sheets, the base URL is that of the style sheet itself, not that of the styled source document. Style sheets embedded within a document have the base URL associated with their container."

**Comment by hober** [comment]
See also https://github.com/w3c/csswg-drafts/issues/3696

**Comment by hober** [comment]
AIUI the JSON-LD folk are comfortable with this outcome, so I'm going to close this issue and consider the review completed. If you'd like us to revisit, please file a new issue and link to this one in it. (@hadleybeeman, if the above resolution isn't to your liking, please reopen this issue.)

Thanks!
