### ISSUE TITLE
Scroll-linked Animations

### ISSUE THREAD

**Issue by stephenmcgruer** [w3ctag/design-reviews#330]
ハウディTAG！

**I'm requesting a TAG review of:**

  - Name: Scroll-linked Animations
  - Specification URL: https://wicg.github.io/scroll-animations/
  - Explainer, Requirements Doc, or Example code: None, please add a comment if the Specification does not suffice
  - Tests: https://chromium.googlesource.com/chromium/src/+/da87860cb19a14c6bc35720bdff3355b84f64407/third_party/blink/web_tests/fast/animation/scroll-animations (in progress of being upstreamed to WPT); https://github.com/web-platform-tests/wpt/tree/master/scroll-animations
  - Primary contacts: stephenmcgruer

**Further details (optional):**

  - Relevant time constraints or deadlines: [please provide]
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://github.com/WICG/scroll-animations/pull/36).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

**You should also know that...**

This feature is currently partially implemented in chromium, hidden behind a flag:

--enable-blink-features=AnimationWorklet

The focus of the implementation was to get something working for [Animation Worklet](https://drafts.css-houdini.org/css-animationworklet/). As such:

1. At the time of writing, it does not work for [Web Animations](https://drafts.csswg.org/web-animations-1/).
2. At the time of writing, the CSS sections of the spec have not been implemented

Some demos can be found at https://scrolltimeline-playground.glitch.me/ . An additional very quickly thrown together demo can be found at https://output.jsbin.com/vezohun/quiet

**We'd prefer the TAG provide feedback as (please select one):**

  - [x] open issues in our Github repo for each point of feedback: https://github.com/WICG/scroll-animations
  - [ ] open a single issue in our Github repo for the entire review
  - [ ] leave review feedback as a comment in this issue and @-notify [github usernames]

**Comment by travisleithead** [comment]
Thanks for filing this review! 

We're excited to see this spec continue to improve.  It looks like there's still quite a bit that still needs to be filled out, and that's OK at an early stage as long as you're aware that there are a bunch more pieces that need to be written.  (For example, what happens if the `<time>` argument to `scroll()` is omitted?)

We note that the web animations spec has high coupling with this proposal... is there an intent to re-integrate into that spec in the future?

**Comment by stephenmcgruer** [comment]
> We're excited to see this spec continue to improve. It looks like there's still quite a bit that still needs to be filled out, and that's OK at an early stage as long as you're aware that there are a bunch more pieces that need to be written. (For example, what happens if the `<time>` argument to `scroll()` is omitted?)

Yes. I think I should have included a bit more of an explainer of where we think the spec is 'at'. Our view is that the imperative (JavaScript) side of the spec is reasonably well developed, but the CSS side has lagged far, far behind and could feasibly be approached with a full rewrite. Very interested in any thoughts on the best way to approach the CSS part. (For example, the spec as it is written currently includes a way to select an element in CSS which is just not a thing as far as we know. It's possible the CSS side may have to be 'weaker' in only having implicit selection of the `scrollSource`.)

>  We note that the web animations spec has high coupling with this proposal... is there an intent to re-integrate into that spec in the future?

Having conferred with the other Web Animations authors, we see Scroll-linked Animations as a separate proposal, that depends on Web Animations (similar to css-animations-2 or css-transitions-2). We do think that one part of this spec, the _general_ concept of the CSS `animation-timeline` property, belongs somewhere like css-animations-2 instead and that Scroll-linked Animations should then define an extension to the `single-animation-timeline` grammar to allow specifying a ScrollTimeline.

**Comment by travisleithead** [comment]
Finished a first look at this during our Tokyo F2f. @dbaron will take a closer look and we'll circle back at the indicated milestone date. Thanks!

**Comment by alice** [comment]
We're coming back to this at our Tokyo face to face, after it dropped off our radar earlier in the year - apologies for our failure to address this in a timely manner.

We notice that there also seems to have been a slow-down of work on this proposal (or has it reached a stable state?), based on the lack of [recent issue activity](https://github.com/WICG/scroll-animations/issues) in your github repo.

Given we don't have an explainer to work off, and that the spec is still somewhat patchy on what problems are being solved, we are going to close this review for now since we can't reasonably make progress on it at this point.

If there is something specific you'd like us to look at (preferably with an [explainer](https://w3ctag.github.io/explainers)), please open a new issue linking back to this one.
