### ISSUE TITLE
Gamepad Light Indicator extension API

### ISSUE THREAD

**Issue by fernando-80** [w3ctag/design-reviews#362]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Gamepad light bar extension

 Explainer:
https://fernando-80.github.io/gamepad-light-indicator-api-draft-explainer.pdf
Spec:
https://fernando-80.github.io/extensions.html

  - Primary contacts: fernando-80 and knyg

We'd prefer the TAG provide feedback as (please select one):
  - [X] open a single issue in our Github repo for the entire review

--------------------------

**Comment by alice** [comment]
The explainer doesn't seem to be public - could you fix the sharing settings? Thanks!

**Comment by fernando-80** [comment]
@alice , my apologies, here's the public version of the explainer document and renderable spec: 

Explainer:
https://fernando-80.github.io/gamepad-light-indicator-api-draft-explainer.pdf
Spec:
https://fernando-80.github.io/extensions.html

Cheers,
Fernando

**Comment by cynthia** [comment]
When can `setColor()`'s promise reject? Preliminary research suggests that the most obvious way to implement this underneath the hood would be raw HID messages, is the idea to reject when the device does not ACK? (I have to actually dig out a controller and see how this works, it's been quite a while since I've had to interact with a HID interface)

I've gone through a bunch of platform APIs and there doesn't seem to be feature parity across platforms to control lighting; how are (non-Chrome) implementations expected to implement this? I would like to see a interoperability story here; `Gamepad.lightIndicators` doesn't mention how the order of the list is ideally expected, which has been a pain point for the users of the Gamepad API with button order.

Since underlying interfaces across platforms is already inconsistent, it's probably not reasonable to expect all platforms with the same controller on different implementations to behave the same, but consistency *within* each platform would be extremely helpful to the users.

One other silly (but not so useful) idea that came to mind is the possibility of using the game controller lights as a side channel for inter-origin "communication", not sure what the security/privacy implications from that would be with a 3 byte wide bus (given a single RGB LED, with multiple the bus size obviously will increase, but it's still only 24 bits of entropy to work with for each LED.), but leaving that for the next person to think about.

**Comment by cynthia** [comment]
While the lights would be a giveaway for the silly idea, it does feel like you could say, use the idle detection API to see if the user is away, do your exchange through flashing lights only when the user is away. Would like to hear if anyone else thought about this.

**Comment by fernando-80** [comment]
> When can `setColor()`'s promise reject? Preliminary research suggests that the most obvious way to implement this underneath the hood would be raw HID messages, is the idea to reject when the device does not ACK? (I have to actually dig out a controller and see how this works, it's been quite a while since I've had to interact with a HID interface)

Hi Cynthia! that's correct, any failure at the gamepad device layer interacting with the OS calls will generate an error which result in the promise being rejected. Each supporting OS may have their particular APIs, but these failures are, for example, error to access logical and physical hardware joystick device information that results getting error instead of the os device_id for the joystick. On top of that, the implementation will also error when trying to set the color with invalid light index (for example, specifying an index beyond the max supported light -1).

**Comment by domenic** [comment]
Regarding the cross-origin communciation with the lights, I don't understand the attack here. Could someone spell it out in more detail? This API seems strictly less powerful than postMessage() when it comes to communication.

**Comment by plinss** [comment]
> Regarding the cross-origin communciation with the lights, I don't understand the attack here. Could someone spell it out in more detail? This API seems strictly less powerful than postMessage() when it comes to communication.

Sangwhan was thinking that the colors could be read back allowing a 3-byte wide communication channel. We don't see that capability in the current draft (might have been in an earlier version?).

**Comment by cynthia** [comment]
Yeah, I re-read the proposal and I got that bit completely wrong. I've scrubbed that part of the feedback; main concerns around consistency (and implementability) are still valid.

**Comment by fernando-80** [comment]
> Yeah, I re-read the proposal and I got that bit completely wrong. I've scrubbed that part of the feedback; main concerns around consistency (and implementability) are still valid.

Agreed! This spec needs to be consistent (with haptic feedback spec) and abstract any platform specific error code. I'll publish a new revision soon. thanks~

**Comment by plinss** [comment]
We're good with this, feel free to ping if there are updates. Thank you for flying TAG.
