### ISSUE TITLE
Storage Quota Usage Details

### ISSUE THREAD

**Issue by jarryd999** [w3ctag/design-reviews#365]
Góðan dag TAG！

I'm requesting a TAG review of:

  - Name: Storage Quota Usage Details
  - Specification URL: https://github.com/whatwg/storage/pull/69
  - Explainer, Requirements Doc, or Example code: https://jarryd999.github.io/quota-usage-details/
  - Tests: https://github.com/web-platform-tests/wpt/tree/master/storage (estimate-usage-details*)
  - Primary contacts: @jarryd999

Further details (optional):

  - Relevant time constraints or deadlines: We would really appreciate feedback by May 20, 2019
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://jarryd999.github.io/quota-usage-details/tag-security-privacy-questionnaire).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify @jarryd999

**Comment by slightlyoff** [comment]
Hey @jarryd999; looks like this isn't scheduled for next week's F2F meeting and is unlikely to get discussion by the requested date as a result.

/cc @alice

**Comment by alice** [comment]
Apologies for missing this. 

We're going through some "growing pains" with our process and (somewhat of a good problem) the number of reviews coming in from Blink; we're hoping to spend some time at the f2f reviewing our process and looking for ways to provide more timely feedback. Not that this helps you in this instance; just that you're certainly not alone in not getting timely feedback from us, and we're acutely aware of the issue.

Meanwhile, I believe we will be triaging issues for review at the f2f, so there is still a chance we'll get to it this week at least.

**Comment by lknik** [comment]
Are you sure you considered all the privacy aspects? It seems this creates a bunch of identifiers with potentially fairly sizable variability in terms of their possible values.

**Comment by pwnall** [comment]
@lknik I'll try to expand on the response to question 3.5 in the security and privacy questionnaire. I don't think we're exposing any new information to origins.

Angle 1: Per-system quota usage (IndexedDB vs Cache Storage vs AppCache etc.) is a function of browser implementation (exposed from the user agent) and of all calls made by an origin to the respective storage APIs. The numbers summarize information that the origin already has.

Angle 2: An origin that has data stored on the client (non-zero quota usage) can store a unique identifier for the user. Instead of using this new API, the origin can simply read a user ID from IndexedDB, or from Cache Storage etc.

For both angles, it's worth noting that when a user wishes to be forgotten by a site and clears the site's data, all client-side storage will be wiped, and the quota details API will report zero usage from all subsystems.

Does this help answer your concerns?

**Comment by lknik** [comment]
For sure it helps. Do we want to have this documented for clarity? For example in Security/privacy considerations?

**Comment by jarryd999** [comment]
@lknik I have added this into the Security/Privacy questionnaire as well as the explainer.

**Comment by pwnall** [comment]
Thank you for your feedback! We are shipping the Storage Quota Usage Details API in Chrome 75.

**Comment by lknik** [comment]
So this API reinforces what is possible with current APIs, good to know ;)

**Comment by lknik** [comment]
Hello,

Just to let you know that this API is being used to detect incognito mode in browsers https://bugs.chromium.org/p/chromium/issues/detail?id=959839

**Comment by dbaron** [comment]
@hober and I are looking at this during a breakout at the TAG face-to-face meeting.

So from a quick read through the explainer I think this largely seems reasonable.

-----

I'm fine with the decision taken regarding the dictionary, although I'm a little skeptical of one of the arguments put forward:
> Cost: we can’t measure if we can remove storage systems without breaking the Web.

I'd understand saying it's harder to measure, but I'm pretty skeptical of the claim that it's impossible.  I think it would require changing the sort of instrumentation being done, but I'd think it would still be possible.

That said, I think the choice of having only systems used be in the dictionary is probably good -- also because one advantage of it was missing, which is that it means that *adding* storage systems doesn't risk breaking web content by adding entries to these dictionaries.

-----

It doesn't seem like the [mechanism used to detect incognito mode](https://mishravikas.com/articles/2019-07/bypassing-anti-incognito-detection-google-chrome.html) doesn't relate to the `usageDetails` feature covered by this review -- although it is concerning and related to the feature more generally.

**Comment by dbaron** [comment]
I think we're fine with closing this issue.  The `usageDetails` on which you've requested review seems like a reasonable addition to the platform.  While we're poking at some deeper issues with `navigator.storage.estimate()` a little bit (see issue linked between this comment and the previous one), I don't think they provide a reason to keep this issue open.

Thanks for requesting TAG review, and sorry for the delay getting back to you.
