### ISSUE TITLE
Largest Contentful Paint

### ISSUE THREAD

**Issue by yoavweiss** [w3ctag/design-reviews#378]
TAG صباح الخير！

I'm requesting a TAG review of:

  - Name: Largest Contentful Paint
  - Specification URL: No spec just yet
  - Explainer, Requirements Doc, or Example code: https://github.com/yoavweiss/LargestContentfulPaint#largest-contentful-paint-explainer
  - Tests: not yet
  - Primary contacts: @yoavweiss, @npm1

Further details (optional):

  - Relevant time constraints or deadlines: [please provide]
  - [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/). The [assessment is here](https://docs.google.com/document/d/1V4oacmZcMU_zWfrKTG6m8BWWcZumjgjK0Bnq_Quq4_c/edit?usp=sharing).
  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

You should also know that...

We haven't settled yet on the ideal [API shape](https://github.com/yoavweiss/LargestContentfulPaint#api-shape) for this feature. Thoughtful opinions on that front will be highly appreciated :)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify @yoavweiss and @npm1

**Comment by dbaron** [comment]
So @hober and I are looking at this in a breakout at the TAG meeting.

It sounds like this is an improvement over First Meaningful Paint.  We're a little bit nervous about heuristics being implementable interoperably across engines, but at the same time we see the value in looking for a good heuristic that provides a sensible measurement for pages that don't do anything special to set themselves up to opt in to more advanced measurements.

We hope that you'll do what you can to make it so that this can be interoperably implemented (e.g., bringing it in to Web Performance, writing a solid specification), particularly if it turns out to be a useful metric.

Thanks @yoavweiss and @npm1 for requesting TAG review, and sorry for taking so long to get to it.
