### ISSUE TITLE
Browser-assisted performance ablation studies

### ISSUE THREAD

**Issue by vsekhar** [w3ctag/design-reviews#442]
Hello TAG!

I'm requesting a TAG review of an early explainer:

  - Name: Browser-assisted performance ablation studies
  - Explainer (containing user needs and example code): https://github.com/vsekhar/browser-ablation/blob/master/README.md
  - Primary contacts (and their relationship to the specification): @vsekhar (proposer)

We'd prefer the TAG provide feedback as (please select one):

  - [ ] open issues in our GitHub repo for each point of feedback
  - [ ] open a single issue in our GitHub repo for the entire review
  - [x] leave review feedback as a comment in this issue and @-notify [github usernames]

Thank you,

Vivek

**Comment by torgo** [comment]
Hi @vsekhar - i think we need more info in order to trigger a review from TAG. It's not clear to me from the explainer how you are using the word "ablation" - also i think we really need to see some consideration of privacy concerns (the security & privacy self check). Also what is the intended venue? The Web Performance wg? Is this something you're thinking of suggesting to wicg?

**Comment by torgo** [comment]
After discussion in our Triage session we've decided to close this issue but if you would like us to re-open please let us know.
