### ISSUE TITLE
Window Controls Overlay for Installed Desktop Web Apps

### ISSUE THREAD

**Issue by amandabaker** [w3ctag/design-reviews#481]
Hello TAG!

I'm requesting a TAG review of Window Controls Overlay for Installed Desktop Web Apps. _(Originally: "Title Bar Customization for PWAs")_

The title bar feature extends the app's client area to cover the entire window, including the title bar area. The web app developer is then able to draw and handle input for the entire window except the window buttons (close, maximize/restore, minimize), which are overlaid on top of the app's canvas.

  - Explainer: https://github.com/WICG/window-controls-overlay/blob/master/explainer.md
  - Security and Privacy self-review: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/218
  - GitHub repo: [WICG/window-controls-overlay](https://github.com/WICG/window-controls-overlay)
  - Primary contacts:
      - Amanda Baker (@amandabaker), Microsoft
      - Jason McConnell (@maggers), Microsoft
  - Organization/project driving the design: Microsoft
  - External status/issue trackers for this feature: [Chrome Status](https://www.chromestatus.com/feature/5741247866077184)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where standardization of this work is intended to be done: CSS Working Group, Web Platform Working Group
  - Existing major pieces of multi-stakeholder review or discussion of this design: 
    - https://github.com/w3c/csswg-drafts/issues/4721
    - https://github.com/w3c/manifest/issues/847
    - https://discourse.wicg.io/t/proposal-title-bar-customization-for-web-apps/4278
  - Major unresolved issues with or opposition to this design: None
  - This work is being funded by: Microsoft

We'd prefer the TAG provide feedback as:

  💬 leave review feedback as a **comment in this issue** and @-notify @amandabaker

**Comment by dbaron** [comment]
Did you intend that those two links to w3c/csswg-drafts issues point to different issues?  (They're the same.)

**Comment by torgo** [comment]
Hi @amandabaker! Thanks for sending this. You've listed WICG - do you have an idea where this goes after incubation?

**Comment by kenchris** [comment]
Hi there,

We are wondering what are the intended venues for these features, like dragable might be intended for CSS WG and the manifest changes for Web Apps WG but where will the JS additions land? Also as part of Web App Manifest?

**Comment by torgo** [comment]
In general we are a bit concerned about specs that explicitly refer to the term PWA, as there is no formal definition. I am a big proponent of the PWA pattern, but specs should probably instead of saying "PWA title bar", it should say "installed windowed web app title bar" or something more related to the underlying technologies such as the manifest file...?

**Comment by kenchris** [comment]
related (with my comments): https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/229

**Comment by kenchris** [comment]
@atanassov you pointed out that this same technology would work for other use-cases than explained in the explainer. Are you following up?

**Comment by kenchris** [comment]
Regarding `unsafe-area-top-inset-left` and `unsafe-area-top-inset-right`: These should work in both RTL and LTR and in other specs we are moving to use `start` and `end` (think flexbox) instead of `left` and `right` @plinss

**Comment by amandabaker** [comment]
We have iterated on the title per some of the feedback here and elsewhere, so I changed it above from "Title Bar Customization for PWAs" to "Window Controls Overlay for Installed Desktop Web Apps". 

---

> Did you intend that those two links to w3c/csswg-drafts issues point to different issues? (They're the same.)
	
@dbaron Not intentional, but I've updated it to include the web app manifest issue
	
> Hi there,
> 
> We are wondering what are the intended venues for these features, like dragable might be intended for CSS WG and the manifest changes for Web Apps WG but where will the JS additions land? Also as part of Web App Manifest?
	
@kenchris  JS changes are targeted for WICG. Currently the discussion has started [here](https://discourse.wicg.io/t/proposal-title-bar-customization-for-web-apps/4278). I also added to the discussion links section above. 
	
>In general we are a bit concerned about specs that explicitly refer to the term PWA, as there is no formal definition. I am a big proponent of the PWA pattern, but specs should probably instead of saying "PWA title bar", it should say "installed windowed web app title bar" or something more related to the underlying technologies such as the manifest file...?
	
@torgo "Installed windowed web app" is what we were intending, so I've updated the title to use that terminology. Thanks for the suggestion!

**Comment by atanassov** [comment]
Since this feature enables PWA's to paint in areas where the window title bar would have been, we identified a concern of impersonating a browser. Most modern browsers today have their tabs UI in the window title bar area, something that's hard to spoof by windowed PWAs and presence of a title bar. In other words, a user could install a PWA that after lunch looks like Chrome for example thus spoofing the user to enter privacy-sensitive data.

**Comment by tomayac** [comment]
`s/lunch/launch/` 
Fun typo in tough times… A little chuckle at the beginning of my work day…

**Comment by torgo** [comment]
Thanks @amandabaker! Looks good. Is there a mitigation against the issue @atanassov raised above?

**Comment by amandabaker** [comment]
@atanassov @torgo We're working on writing up some of the mitigation options that we've come up with so far, so I'll share that out shortly

**Comment by kenchris** [comment]
@amandabaker any update?

Also there is now this related proposal from Google (at least touching the display values):

https://github.com/dmurph/display-mode/blob/master/explainer.md

**Comment by amandabaker** [comment]
We have a few new mitigation proposals listed in our [Security and Privacy Review doc](https://docs.google.com/document/d/1l7z7Y88lhL9r_0y5S-pcYGaFJqUkaPKSDcgRRTIyj6c/edit?usp=sharing). Access to the doc is currently limited, so feel free to request access if you don't have it already. 

Although the proposals in the doc are specific to Chromium, the concepts behind them can be applied to any browser.

**Comment by torgo** [comment]
Hi @amandabaker sorry but can you please migrate that doc to an appropriate place in git hub or at least turn on View permission for anyone who has the link?  Many thanks.

**Comment by amandabaker** [comment]
@torgo I've updated the permissions on the doc. Let me know if you still have issues accessing it

**Comment by torgo** [comment]
Due to holiday schedules we've had to bump discussion on this to the week after next. Sorry for the delay on our side @amandabaker.  If there are any updates in the mean time please feel free to let us know here.

**Comment by amandabaker** [comment]
Just as a heads up, we moved the explainer into it's own WICG repo here: https://github.com/WICG/window-controls-overlay/blob/master/explainer.md

I also updated the original post to reflect the new location of the explainer

**Comment by kenchris** [comment]
Web App Manifest is close to integrate display_override (https://github.com/w3c/manifest/pull/932) but the explainer is not using that yet.

**Comment by torgo** [comment]
Hi @amandabaker - we're just discussing in the TAG "f2f" today and it seems to me that some potential privacy issues are not being taken into account. Specifically:

The point of PWAs is to have app-like experiences that have the same safety guarantees as the rest of the web - so if we're allowing developers to write arbitrary stuff into trusted UI then this can be a problem. It does not seem like there are sufficient mitigations. For example, a PWA could write confusing or misleading UI elements into the title bar in order to trick the user into disclosing private information (e.g. a phishing attack making it looks like their bank and taking their username and password). 

Yes, we're talking about web apps that are installed but I'm also concerned that the web app could be installed under false pretences - where the user's trust is gamed by a web site or malicious advert for example, or via a URL they receive by text message or otherwise out of band...

It feels to me like this needs to be in the Privacy section and some mitigations need to be discussed here?

**Comment by amandabaker** [comment]
Hi @torgo, we have heard a lot of concerns about security and spoofing and have been discussing implementing a way to toggle between a normal standalone titlebar and the window controls overlay. When an app is installed that supports window controls overlay, by default it opens in standalone mode. Then from a button in the titlebar, the user can choose to toggle into this unsafe state. We are still discussing how best to notify the user of exactly what area can be trusted (e.g. highlighting bounds of UA-controlled region when toggling between modes).  

Would this help to resolve the privacy issues? If so, I can update the explainer to include this mitigation. Also, we have a doc with other mitigation options if this approach is still insufficient: https://docs.google.com/document/d/1l7z7Y88lhL9r_0y5S-pcYGaFJqUkaPKSDcgRRTIyj6c/edit?usp=sharing

**Comment by kenchris** [comment]
I think it solves it partially and I even suggested this idea to @torgo in our breakout today.

I also think that if we can detect that the titlebar UI changed radically (maybe look at fuzzy comparing average color etc) then we would toggle back to standalone mode or so

**Comment by amandabaker** [comment]
@kenchris I worry that detecting differences in the UI would be harmful to both the user and the developer:
1. For "good" apps, it limits the amount of change that is permissible in the title bar, making them less customizable and likely a worse experience for users.
2. For malicious apps, it just forces the developer to work harder to spoof, but it doesn't _prevent_ spoofing.
3. For any app, the dev needs to experiment to figure out how much can change before toggling the standalone title bar. This is bad for "good" devs, but still won't stop the bad ones.
4. Due to minor style/font differences across OSes, devs would have to validate their changes on all platforms to ensure that the title bar did not toggle back to standalone.

Also, I think it would be difficult to agree upon an acceptable amount of change.

**Comment by kenchris** [comment]
It should be per platform, by saving info from rendering. Chrome already has pixel rendering tests that does something similar. 

All that would happen if it detects a large change is expand back to regular titlebar, and the user can easily collapse it to the custom toolbar again.

**Comment by kenchris** [comment]
Anyway you don't have to implement this, but I think it is worth listing or exploring as a mitigation strategy. 

It is good to have potential mitigation strategies listed in case we start seeing abuse cases

**Comment by kenchris** [comment]
With regard to 1. I was mostly considering the state of the toolbar after a reload or restart of the app, but it being dynamic while the app is running (is entering data in search bar) 

I mostly thing the phishing attempts will be pretending to be another app after relaunch, but I might be wrong.

In which case it could be extended to visibility change as apps probably shouldn't change the toolbar while invisible - or it would be interesting to hear use cases for doing that

**Comment by kenchris** [comment]
What is this current status of this? 

I see that `"display_override"` is shipping in next Chrome version (M89) on desktop. https://chromestatus.com/features/5728570678706176 - I assume this is blocking on that?

Is there anything in particular that you would like our help with?

**Comment by abflow** [comment]
@atanassov, impersonation of the browser is indeed a concern to be taken seriously.

In the issue mentioned above by @amandabaker, one suggested a frameless media feature that would allow total customization of window controls with HTML and CSS, while providing security enhancement.

In fact, impersonation of the browser can potentially be found in three browser features:

- Fullscreen Mode
- Picture-In-Picture for arbitrary content ([chromium feature](https://chromestatus.com/feature/4844605453369344))
- Windows control overlays (this proposal)

It indicates that it is not sufficient to rely on visual cues in the UI for security features. The thing to note is that a malicious website may not need to be pixel perfect to abuse users, as they primarily exploit their inattention. Therefore, a window controls overlay does not offer more security than custom window controls designed from scratch in HTML and CSS.

The main security issue is indeed the potential misuse of iframes and portals, allowing the impersonation of the browser by a malicious website acting as a middleman spying onto the users. That's why one is suggesting several security features for the frameless media feature that one is suggesting:

**Security model for frameless media feature**

1. The frameless media feature would use the "[Trusted Web Activity](https://blog.chromium.org/2019/02/introducing-trusted-web-activity-for.html)" security model, and by default, it would disallow the use of third-party domains in iframes and web portals, making it impossible to impersonate the browser into a webpage. Third-party domains in iframes and portals could be allowed only when the hosting page is localhost.
2. At load time, the browser would check the presence of the frameless media query into the active stylesheet as well as the visibility of the custom window controls into DOM. If the controls are not available, the browser would fall back to the default browser display mode, or to the "[display-override](https://chromestatus.com/features/5728570678706176)" mode.

This way, the frameless webpage would not depend on the attention of the user to visual cues into the UI in order to be secure and would prevent malicious websites to block the user into the page with no window controls.

**Comment by abflow** [comment]
We have to bear in mind that PWA is not a standard but just an experiment on what could be a desktop-like application feeling in browsers. Mozilla already dropped support for PWA for a reason. It has way too many limitations both for users and developers.

What developers and users really need for having the convenience of desktop applications built on top of browser technologies is not only a customizable frame, such as with a frameless media feature in CSS, but also a security model allowing to run arbitrary programs onto the desktop, such as spinning a local web server from the application UI frame.

Similar to "[Trusted Web Activity](https://blog.chromium.org/2019/02/introducing-trusted-web-activity-for.html)" into the browser, we would need a "Trusted Desktop Activity" security model, that would give permission to a website/webpage application to run a program onto the local machine, to access certain parts of the filesystem, to allow network requests, etc., a bit like Deno's [permissions-based security model](https://deno.land/manual/getting_started/permissions) is doing.

**Comment by abflow** [comment]
As for using browser technologies as desktop applications GUI, apparently, browser manufacturers do not want that to happen. In fact, they do not want that developers and users interface the browser with their local machine.

I personally suspect that this technological lock-in imposed to web users by browser manufacturers in the name of security (sandbox) is in fact a commercial strategy that is at the origin of the "cloud" platform.

Big money is made by cloud enterprises just because users can not use their local machine with web technology, so that they push them to put all their documents and information in the cloud, instead of just using the local machine from the browser. Google wants to appear as the good guy and has initiated the PWA patterns, but it is clearly a way to diminish the frustration of developers, and remains a very limited and incomplete approach diluted in time.

Also, strangely, Firefox presently seems to actively unpromote the use of HTML UI and browser technology for building desktop applications (no Filesystem Access Api, no installation of PWA, no standalone GUI mode, etc)...

One could think that an open-source browser like Firefox which supposedly has no financial interest in preventing the users to interface with their local machine from within the browser would work to remove the limitations between the browser and the local machine, but in fact it happens that they are amongst the ones who in the recent years actively unpromote the development of features removing those limitations.

Perhaps donators to the Mozilla Foundation also happen to be cloud entreprenors or companies ? Yes, indeed... according to wikipedia, "In 2006, the Mozilla Foundation received US$66.8 million in revenues, of which US$61.5 million is attributed to "search royalties" from Google"...

Presently, I can now clearly picture, in the name of an imaginary "security", a big conspiration of browser manufacturers against web developers and web users so that they could not interface with their local machine from the web platform, a conspiration built over the years through vested interests contradictory to the neutrality and freedom of the internet.

**Comment by kenchris** [comment]
Since last, we see that "display_override" has shipped in Edge and Chrome.

Google also made an article about it here: https://web.dev/window-controls-overlay/

**Comment by kenchris** [comment]
From the article:

> Spoofing #
> Giving sites partial control of the title bar leaves room for developers to spoof content in what was previously a trusted, browser-controlled region. Currently, in Chromium browsers, standalone mode includes a title bar which on initial launch displays the title of the webpage on the left, and the origin of the page on the right (followed by the "settings and more" button and the window controls). After a few seconds, the origin text disappears. If the browser is set to a right-to-left (RTL) language, this layout is flipped such that the origin text is on the left. This opens the window controls overlay to spoof the origin if there is insufficient padding between the origin and the right edge of the overlay. For example, the origin "evil.ltd" could be appended with a trusted site "google.com", leading users to believe that the source is trustworthy. The plan is to keep this origin text so that users know what the origin of the app is and can ensure that it matches their expectations. For RTL configured browsers, there must be enough padding to the right of the origin text to prevent a malicious website from appending the unsafe origin with a trusted origin.

**Comment by atanassov** [comment]
During our May 2021 vf2f @torgo, @kenchris and myself took another look at this issue. Overall we are still concerned about the lack of multistakeholder interest. At the same time there has been sufficient efforts made to ensure our concerns about spoofing have been addressed, thus we are happy to close the issue. Good luck and thank you for working with TAG.
