### ISSUE TITLE
review HTML event loop and how things fit into it

### ISSUE THREAD

**Issue by dbaron** [w3ctag/design-reviews#489]
Hello TAG!

This is a continuation of the discussion in #197 because the things that I've been keeping that open for aren't really specific to `IntersectionObserver` anymore.

However, I think we do need to further review the HTML event loop, make sure it's specified clearly enough for new things to slot into it in an interoperable way, etc.

There's a bunch of prior discussion in the above issue and also in a bunch of other issues linked from it.

**Comment by dbaron** [comment]
Note that related issues are whatwg/html#3246 and maybe w3c/IntersectionObserver#263.

**Comment by hober** [comment]
I think we should try to set aside some F2F time for this one.

**Comment by hober** [comment]
@dbaron and I looked at this in our May 2020 F2F. We're going to file an issue on CSS to define when batching and flushing happens, so that HTML can hook into those definitions properly. This will help avoid ambiguity like the one @dbaron and @rniwa encountered in this area (where @dbaron thought the text was talking about default style layout flush timing, and @rniwa thought it was talking about paint timing).

**Comment by atanassov** [comment]
@hober and I looked at this during our London F2F today. The core problem of this HTML event loop issue sits with the CSSWG and pending further discussions and definition (see https://github.com/w3c/csswg-drafts/issues/5115). Until there is progress made, there is not much we can do at the TAG.

**Comment by hober** [comment]
The CSSWG (Emilio and @dbaron, specifically) agreed to take up the batching & flushing issue at a recent CSSWG F2F, so we're closing this at our end. We look forward to seeing where they get with this.
