### ISSUE TITLE
Schemeful Same-Site

### ISSUE THREAD

**Issue by sbingler** [w3ctag/design-reviews#497]
Hello TAG! 

I'm requesting a TAG review of Schemeful Same-Site.

The SameSite cookie attribute is designed to defend against CSRF attacks but currently does not take the scheme of the site into account. This was originally to assist sites during their transition to https, however it results in the secure and insecure versions of the same host being considered same-site. A network attacker could thus impersonate http://site.example and use it to bypass SameSite protections on https://site.example. Between this security flaw and HTTPS usage markedly increasing, we believe it is time to change this definition.

Modify SameSite’s implementation in the user agent to consider origins with different schemes as cross-site. Thus https://site.example and http://site.example would now be considered cross-site.

  - Explainer : https://github.com/sbingler/schemeful-same-site
  - Spec: https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html#rfc.section.3.3
  - Security and Privacy self-review: I'm not sure this applies, please correct me if I'm wrong, as this proposal doesn't expose anything new.
  - Primary contacts (and their relationship to the specification):
      - Steven Bingler (@sbingler, Google)
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature: https://www.chromestatus.com/features/5096179480133632

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): IETF
  - The group where standardization of this work is intended to be done ("unknown" if not known): IETF
  - Existing major pieces of multi-stakeholder review or discussion of this design: None
  - Major unresolved issues with or opposition to this design: N/A, unknown
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @sbingler

**Comment by annevk** [comment]
This is a subset of #483, right? How do these relate?

**Comment by chlily1** [comment]
This is not a strict subset of "Scheme-bound cookies".

For example: Let's say we navigate to a page with an iframe such as
```
http://foo.com (top level)
 -> https://foo.com (iframe)
```

And some cookies such as: 
- `secure_lax=foo; SameSite=Lax; Secure` (set from https://foo.com)
- `secure_none=foo; SameSite=None; Secure` (set from https://foo.com)
- `insecure_https_lax=foo; SameSite=Lax` (set from https://foo.com)
- `insecure_http_lax=foo; SameSite=Lax` (set from http://foo.com)

In the "Schemeful Same-Site" world:
- The `https://foo.com` iframe gets `secure_none` but no other cookies. (Since `https://foo.com` is cross-site from `http://foo.com` only SameSite=None is allowed.)
- The `http://foo.com` main frame gets both the insecure lax cookies: `insecure_https_lax` and `insecure_http_lax`.

In the "Scheme-bound cookies" world:
- The `https://foo.com` iframe gets `secure_none`, `secure_lax`, `insecure_https_lax` as they were all set from the secure scheme. (And `foo.com` is the site in both cases so SameSite=Lax is ok.)
- The `http://foo.com` main frame gets `insecure_http_lax` and no other cookies. (As it was the only one set from the insecure scheme.)

Of course we could also apply both:
- The `https://foo.com` iframe gets only `secure_none`.
- The `http://foo.com` main frame gets only `insecure_http_lax`.
-

**Comment by sbingler** [comment]
Thank you Lily for your explanation, exactly.

Another way to look at the two is that: 

- **Schemeful same-site** determines which sites/iframes/sub-resources/etc are allowed to interact (send/set) with the available cookies in the cookie jar.
  -  http://site.example and https://site.example would be treated as if they were as different as https://site.example and https://othersite.example for purposes of same-site.

- **Scheme-bound cookies** splits up the cookie jar such that an insecure site will only have cookies set by an insecure scheme (which were therefore placed into the insecure cookie jar) available to it.

**Comment by kenchris** [comment]
Why was the name schemeful used instead of scheme-bound? I am not clear of the difference between the words

**Comment by torgo** [comment]
So ... is this a competing proposal? Or is it complimentary. Trying to understand how developers will see this and be able to make sense of it....

**Comment by torgo** [comment]
The explainer as it is is very light on user needs. Can you please put this in context a bit more and explain what problem it's trying to solve?

**Comment by sbingler** [comment]
Tl;dr: “Schemeful same-site” affects the browsing contexts cookies will be sent in.
“Scheme-bound cookies” affects the connections the cookies will be sent on.

Thanks for your feedback Kenneth and Daniel!

I’d like to start off by prefacing that understanding the differences between schemeful same-site and scheme-bound cookies can be difficult; It’s subtle and can be confusing.

The two proposals complement each other (@torgo) by each trying to move cookies closer to an origin based security model. At present, cookies are shared between secure and insecure browsing contexts, and secure and insecure network connections. The first vulnerability is the target of "Schemeful same-site" while the second is addressed by "Scheme-bound cookies". 
“Schemeful same-site” protects secure origins from potentially-compromised insecure origins by allowing the SameSite attribute to protect a cookie from being sent in a mixed-scheme browsing context.
“Scheme-bound cookies” protects secure origins from potentially-compromised insecure origins by binding a cookie to the secureness of its source origin’s scheme and preventing it from being accessed on any insecure connection.

This similarity in their goal inevitably leads to overlap in their proposed behavior. However one is not a strict subset of the other, as shown in [Lily’s previous post](https://github.com/w3ctag/design-reviews/issues/497#issuecomment-613496794). Notice which cookies are included changes depending on which proposals are active: just schemeful same-site, just scheme-bound cookies, and finally both.

Communicating this successfully to developers is clearly not going to be easy and “how” isn’t a question I can fully answer at the moment. Same-site (current) was/is also a complicated concept but a lot of work has gone into communicating to developers about what it means for them and how they can successfully adopt it e.g. [this article](https://web.dev/samesite-cookies-explained/).
I’m hoping 1) my proposal is easy enough to understand for devs as simply a modification of what they know about same-site. I.e. the current world + “different scheme means cross-site” and 2) a similar communication effort can be made for scheme-bound cookies.

As to why the name “schemefully same-site” (@kenchris) vs something else I chose the name to illustrate that this is a modification/extension of (the current) same-site which only considers the registrable domain as defining a “site.” This new proposal now considers the scheme as well, hence schemefully. Could it be called scheme-bound same-site? Maybe, but it feels strange to me.

Scheme-bound cookies on the other hand makes sense to me in that you are binding the cookies to the scheme of the source that set it. So if a secure source sets a cookie then an insecure source can’t possibly get to it (ignoring any temporary carve outs) and vice-versa. @mikewest Please weigh in if you have any thoughts.

As to the explainer (@torgo) could you expand a bit on what you think would be helpful? I made mention of the user benefits in the goals (extending the CSRF protections to the schemed site) and tried putting the context in the introduction. Given your experience with explainers how could I make this more clear? 

Cookies are one of the last components of the web platform that blur the lines between secure and insecure origins, and both of these proposals are designed to harden different boundaries in order to increase the trustworthiness of the Web platform.

**Comment by mikewest** [comment]
I have thoughts! In no particular order:

1.  Chromium, at least, seems interested in shipping both of the behaviors in question. Talking about them as distinct behavioral changes makes it possible to ship pieces when they're ready, rather than waiting for the stars to align for a big-bang shift, but they're both part of the same story around [incrementally improving cookies' security and privacy properties](https://mikewest.github.io/cookie-incrementalism/draft-west-cookie-incrementalism.html).

2. Hand-waving a bit: RFC6265bis currently [defines](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-06#section-5.2) "same-site" as a registrable domain match between two origins. HTML [defines](https://html.spec.whatwg.org/#sites) "schemelessly same-site" as more or less the same thing, and also defines "same-site" as a registrable domain match _and_ a scheme match. That's more or less what @sbingler is proposing here: "schemefull same-site" will align the `SameSite` cookie attribute with HTML's existing "same-site" concept, rather than its "schemeless same-site" concept.

3.  We originally defined cookies `SameSite` attribute to equate HTTP and HTTPS variants of a site as a mechanism to ease upgrades for sites that had non-secure pages relying upon secure SSO endpoints (e.g. `http://example.com/` embedding `https://login.example.com/`). It does allow vulnerabilities in those relationships, as anything `https://login.example.com/` passes to `http://example.com/` is exposed to the network. At the time, it was a reasonable carveout to allow migration from non-secure to secure pages. Given the shift to HTTPS over the last few years, we're hopeful that it's a carveout that's no longer necessary.

**Comment by torgo** [comment]
Ok we're planning to close this issue. We support the proposal. Thank you for flying TAG.
