### ISSUE TITLE
Behavior of the "disabled" attribute for HTMLLinkElement

### ISSUE THREAD

**Issue by mfreed7** [w3ctag/design-reviews#519]
Hello TAG!

I'm requesting a TAG review of the behavior of the "disabled" attribute for HTMLLinkElement.

This request is being made at the suggestion of @slightlyoff in this [Intent to Ship thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/3izM5vVo98U/iDLjz_TwAgAJ). This change is an interop-improvement, as the "disabled" attribute was previously poorly specified, and implementations differed. There is a more general need to specify the "disabled" attribute for HTMLStyleElement and SVGStyleElement, and this is discussed [here](https://github.com/whatwg/html/issues/1081) and [here](https://bugs.chromium.org/p/chromium/issues/detail?id=695984). Perhaps the TAG could weigh in on either the HTMLLinkElement specifically, or these issues generally?

  - Explainer¹ : https://github.com/whatwg/html/issues/3840 (actually just the issue thread)
  - Specification URL: https://github.com/whatwg/html/pull/4519 (a PR)
  - Tests: https://wpt.fyi/results/css/cssom?label=master&label=experimental&aligned=&q=htmllinkelement-disabled
  - Security and Privacy self-review²: N/A
  - GitHub repo (if you prefer feedback filed there): N/A
  - Primary contacts (and their relationship to the specification):
      - Mason Freed (@mfreed7), Google
      - Emilio Cobos Álvarez (@emilio), Mozilla
  - Organization(s)/project(s) driving the specification: Google, Mozilla 
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/whatwg/html/issues/3840 
  - External status/issue trackers for this specification: https://chromestatus.com/feature/5110851973414912

Further details:

  - [X] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: None
  - The group where the work on this specification is currently being done: WhatWG
  - The group where standardization of this work is intended to be done: WhatWG
  - Major unresolved issues with or opposition to this specification: Just compat
  - This work is being funded by: Google/Mozilla

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @mfreed7, @emilio

**Comment by annevk** [comment]
What kind of support exists for `<style>`? With
```html
<style>body { background:lime</style>
<style disabled>body { background:red</style>
```
I get red in each browser.

**Comment by emilio** [comment]
Yes, the content attribute doesn't exist for `<style>`. The WebIDL attribute does though, and it forwards to the underlying `.sheet` (so `style.disabled = true;` is effectively `if (style.sheet) style.sheet.disabled = true;` and so on.

**Comment by alice** [comment]
I note from the linked intent to implement and ship thread that this is more of an FYI:

@slightlyoff:
> If there's a larger project to do here regarding the `disabled` attribute behaving consistently across elements, that's something they can weigh in on and, if they support, can help drive.

So, for the purposes of the implementing and shipping, no need to block on us; we will discuss whether there is more work to explore here and comment here if we have any thoughts.

**Comment by hober** [comment]
How does the integration with CSSOM's `disabled` attribute work?

**Comment by alice** [comment]
(Working notes)

There was mention in the original bug(s) about HTMLStyleElement and SVGStyleElement, but the PR on HTML only seems to address HTMLLinkElement. We should follow up what happened with the other two.

**Comment by dbaron** [comment]
So one thing I'm trying to understand is how dynamic changes of `disabled` are processed.  It seems like the change to the "linked resource fetch setup steps" means that the stylesheet isn't even loaded -- and then I think the change to "The appropriate times to fetch and process this type of link" means that changing `disabled` would mean that it causes the style sheet`s CSSOM representation to be dropped?  Is that correct?  (And is it desirable?)

If it's not correct... then what causes setting the `disabled` attribute to disable the stylesheet?

**Comment by emilio** [comment]
> So one thing I'm trying to understand is how dynamic changes of disabled are processed. It seems like the change to the "linked resource fetch setup steps" means that the stylesheet isn't even loaded -- and then I think the change to "The appropriate times to fetch and process this type of link" means that changing disabled would mean that it causes the style sheet`s CSSOM representation to be dropped? Is that correct? (And is it desirable?)

Yes, that's correct and intentional. `<link rel=stylesheet disabled>` has `link.sheet == null;`. It indeed doesn't even load the stylesheet if the attribute is present in the first place.

This matches WebKit / Blink's behavior when coming from the parser (they had a quirk where if you remove and add the attribute again after loaded, it'd behave differently in somewhat odd ways). See https://github.com/whatwg/html/issues/3840#issuecomment-481034206 for context.

When disabled is removed, then stuff is processed normally, except for the "explicitly enabled" bit, which also makes alternates to work.

**Comment by emilio** [comment]
> How does the integration with CSSOM's disabled attribute work?

They're completely independent. `HTMLLinkElement.disabled` just reflects the `disabled` element on the `link`. This is, I'd note, different from `HTMLStyleElement.disabled` and `SVGStyleElement.disabled`, which just forward to their inner stylesheet.

Firefox used to make `HTMLLinkElement.disabled` (the WebIDL attribute) behave just like `HTMLStyleElement.disabled` and `SVGStyleElement.disabled`, but we had to change it for compat reasons because people were using the link attribute, and here we are now.

Note that I intentionally proposed to make them two completely separate mechanisms, because figuring out a sane interaction between the CSSOM disabled flag and the link element felt really weird (setting `link.sheet.disabled = true` should ideally then also reflect on the link's attribute?). That also didn't match any engine.

So I went with a compromise described in the comment above.

**Comment by emilio** [comment]
> (Working notes)
> 
> There was mention in the original bug(s) about HTMLStyleElement and SVGStyleElement, but the PR on HTML only seems to address HTMLLinkElement. We should follow up what happened with the other two.

HTMLStyleElement and SVGStyleElement have a `disabled` WebIDL attribute, but not a `disabled` html attribute... This is all more messy than it should, I know.

Ideally either:

 * The `<link disabled>` attribute wouldn't do anything special and all the WebIDL attributes would do the same thing in all the relevant elements. This is what Gecko used to implement, but had to implement the attribute for compat.

 * Maybe we also implement `<style disabled>`, behaving the same as `<link>`? That may be nice, though on the other hand the "explicitly enabled" stuff is a bit hackish, so not a fan of making it apply to all `LinkStyle`s... Still may be a better end state.

**Comment by dbaron** [comment]
>     * Maybe we also implement `<style disabled>`, behaving the same as `<link>`? That may be nice, though on the other hand the "explicitly enabled" stuff is a bit hackish, so not a fan of making it apply to all `LinkStyle`s... Still may be a better end state.

That seems somewhat problematic given the existence of `disabled` on `HTMLStyleElement`, since it would be weird to add a `disabled` attribute to `<style>` without having it reflected to JS as `disabled`.  So it seems like the solution of having `disabled` on `<link>` be a totally different thing from what it is on `<style>` is probably less horrible than the compatible alternatives.

**Comment by dbaron** [comment]
Also, to comment on the original question:  it sounds like it would have been nice to have more consistent behavior across elements, but based on @emilio's comments and the need that we found the need to implement inconsistent behavior in Gecko for compatibility, it sounds like that's not an option, and it feels like this PR has resolved some real interop problems.

**Comment by plinss** [comment]
Closing this, the TAG is happy to see this moving forward.
