### ISSUE TITLE
Cross-origin opener policy reporting API

### ISSUE THREAD

**Issue by camillelamy** [w3ctag/design-reviews#527]
Saluton TAG!

I'm requesting a TAG review of Cross-origin opener policy API.

We want to provide a reporting API for cross-origin opener policy (COOP) to help developers deploy it on their websites. In addition to reporting breakages when COOP is enforced, we want to provide a report-only mode for COOP. The report-only mode for COOP will not enforce COOP, but it will report potential breakages that would have happened had we enforced COOP.

  - Explainer: [https://github.com/camillelamy/explainers/blob/master/coop_reporting.md](https://github.com/camillelamy/explainers/blob/master/coop_reporting.md)
  - Security and Privacy self-review: Inside the explainer.
  - Primary contacts:
      - [Camille Lamy](https://github.com/camillelamy): Google, Chromium implementer
  - Organization/project driving the design: Chromium 
  - External status/issue trackers for this feature: [Chrome Status](https://www.chromestatus.com/feature/5755687994916864), [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1059303)

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done: [WHATWG](https://github.com/whatwg)
  - The group where standardization of this work is intended to be done: [WHATWG](https://github.com/whatwg)
  - Existing major pieces of multi-stakeholder review or discussion of this design: [GitHub issue](https://github.com/whatwg/html/issues/5260)
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Google

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  🐛 open issues in our GitHub repo for **each point of feedback**

Thank you!
Camille

**Comment by mikewest** [comment]
@torgo: We're filing this a bit later than we should have, but it would be helpful to get y'all's eyes on it sooner rather than later, as our implementation is underway, and we think it's on the critical path for deployment of this isolation primitive at scale (which, in turn, is blocking our ability to deprecate unsafe usage of `SharedArrayBuffer`-likes). Thanks!

**Comment by plinss** [comment]
I understand there's the precedent with CSP, but curious if there's another reason this is a separate header rather than a `report-only` flag on the normal COOP header?

**Comment by mikewest** [comment]
We think it's valuable to be able to report upon one policy, while enforcing another. This gives folks the ability to migrate from the weaker `same-origin-allow-popups` to the stricter `same-origin` by enforcing the former, and reporting upon the latter. Once they drive the reports down to a point at which they're happy, they can enforce the latter.

It's certainly plausible to obtain this result by specifying the reported policy via a syntax that jammed everything into one header. I think we've taken a multi-header approach here ([and in COEP](https://wicg.github.io/cross-origin-embedder-policy/#COEP-RO)) simply for consistency with things like CSP rather than any practical reason unique to this mechanism.

**Comment by annevk** [comment]
(It's not just consistency. It's also extensibility. If the policies would become more complex than an enum value that might become quite hard to handle.)

**Comment by plinss** [comment]
Thanks for the responses, we discussed this further and agree with the use case for a separate header. We're also fine with the current design.

Closing this as satisfied, thanks for flying TAG.
