### ISSUE TITLE
Compute Pressure API

### ISSUE THREAD

**Issue by oyiptong** [w3ctag/design-reviews#621]
Ya ya yawm TAG!

I'm requesting a TAG review of the Compute Pressure API.

We propose a new API that conveys the utilization of CPU resources on the user's device. This API targets applications that can trade off CPU resources for an improved user experience. For example, many applications can render video effects with varying degrees of sophistication. These applications aim to provide the best user experience, while avoiding driving the user's device in a high CPU utilization regime.

High CPU utilization is undesirable because it strongly degrades the user experience. Many smartphones, tablets and laptops become uncomfortably hot to the touch. The fans in laptops and desktops become so loud that they disrupt conversations or the users’ ability to focus. In many cases, a device under high CPU utilization appears to be unresponsive, as the operating system may fail to schedule the threads advancing the task that the user is waiting for.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/WICG/compute-pressure/blob/main/README.md
  - Security and Privacy self-review²: https://github.com/WICG/compute-pressure/blob/main/security-privacy-self-assessment.md
  - GitHub repo (if you prefer feedback filed there): https://github.com/WICG/compute-pressure/
  - Primary contacts (and their relationship to the specification):
      - Kenneth Christiansen (@kenchris), Intel
      - Arnaud Mandy (@arskama), Intel
      - Anssi Kostiainen (@anssiko), Intel   
      - Victor Costan (@pwnall), Google
  - Organization/project driving the design: Google/Fugu
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5597608644968448

Further details:

  - [✔️] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future):
    - WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known):
    - WebPerf WG
  - Existing major pieces of multi-stakeholder review or discussion of this design:
    - https://bugs.chromium.org/p/chromium/issues/detail?id=1067627
  - Major unresolved issues with or opposition to this design:
    - Currently none
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by kenchris** [comment]
We reviewed this during breakouts this week. Since all use cases listed relate to web applications responding to high load, we are wondering if a simpler, less granular, more high level API would address these use cases equally well, without the added complexity of specific thresholds, different for CPU utilization and CPU speed. See [Prefer Simple Solutions](https://w3ctag.github.io/design-principles/#simplicity).

If not, it would be good to show use-cases where this is not the case. We assume the reason might be to know well ahead whether you are about to get throttled and it is less interesting knowing when you are being throttled. Is that correct?

We understand that all speeds are being rescaled to a percentages, instead of revealing actual top speeds etc which really helps with privacy, so we welcome that.

In terms of the proposed API, please note that all other observers on the Web Platform today use `observer.observe()` instead of `observer.start()`. Also, while it's good that debugging use cases were considered, we think that a test mode would be more appropriate as a browser dev tools switch instead of part of the API surface. 

The spec has to handle heterogenous computing where the CPU has different kinds of cores (ARM BIG.little, Intel Alder Lake). The software/hardware scheduler can move workloads (such as browser process) to another core with different characteristics, like you might be about to max out the little cores, then you are moved to another core with plenty of performance budget left. This may lead to confusing numbers when it is expressed as a single scalar.

There are other places on the web platform where you might get throttled as if you are a background tab. It this only for visible focused documents, or similar?

**Comment by kenchris** [comment]
Hi there,

Discussed this with @LeaVerou today in a breakout and we think it would be great if the explainer could better explain the difference (from dev point of view) between clock speed and utilization, in a way that shows clearly why both are needed.

Some users might not understand or care about the difference and it will be unclear for them what value to use.

**Comment by torgo** [comment]
As discussed today we'll come back to this after next month (in October).

**Comment by cynthia** [comment]
@LeaVerou and I discussed this briefly (as there wasn't any feedback so far) during our VF2F and noticed that there is some pushback from other implementors. Has risk mitigation of this feature been discussed with other implementors?

**Comment by torgo** [comment]
It seems like this work might be delayed? We're going to put this on a milestone for our next virtual f2f to have a look at it again but please ping us if there is further progress.

**Comment by kenchris** [comment]
Hi there! Intel is taking the lead on this API now that @oyiptong left Google, and we will need a bit of time for the transition to get on top of all the details.

@arskama and I will take over, still in collaboration with people at Google.

We could set a different milestone (maybe January?) or close this and reopen when we are ready. What do people prefer? @pwnall @arskama @anssiko

**Comment by arskama** [comment]
We are with @kenchris and @anssiko redoing the explainer and specifications.
I would also suggest that we close this one and re-open a new one whenever we are ready for review.

**Comment by LeaVerou** [comment]
Sure!

**Comment by martinthomson** [comment]
See #795 for the successor of this issue.
