### ISSUE TITLE
[css-color-adjust-1] Privacy Impact of System Colors in Forced Colors Mode

### ISSUE THREAD

**Issue by fantasai** [w3ctag/design-reviews#637]
It's not really a dispute escalation yet, but we'd like the TAG's review specifically on https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752

See https://github.com/w3ctag/design-reviews/issues/583 for general info about the spec.

We'd prefer the TAG provide feedback as (please select one): leave a comment in the following GitHub issue:  https://github.com/w3c/csswg-drafts/issues/5710

Thanks~

**Comment by torgo** [comment]
Comments coming after discussion in [today's breakout](https://cryptpad.w3ctag.org/code/#/2/code/view/1IBqf80Qykz6z3byRkMKbAffG0uuu+fKlsV52-Asudc/).

**Comment by atanassov** [comment]
We had a chance to discuss this issue with all TAG members over few different breakout sessions. The overall consensus on the issue is that we prefer to scope the exposure of system color information while preserving the ability of authors to take advantage of  system features such as dark mode or high contrast media features.

In order of preference, we recommend that system color values are serialized as their color keywords through getComputedStyle(). Knowing that this will introduce compatibility issues, our next recommendation is that CSSWG considers exploring the option of creating a special group of color values that are always serialized as their defaults (i.e. lie about the values), similar to the way `:visited` pseudo is handled today (options `2` and `3` respectively in issue #583). If neither of these two approaches is achievable we recommend continuing with the status quo of option `1`.
