### ISSUE TITLE
User Timing 

### ISSUE THREAD

**Issue by caribouW3** [w3ctag/design-reviews#642]
Ya ya yawm TAG!

I'm requesting a TAG review of User Timing.

This is actually a request to confirm or amend previous review, as requested in the CR transition
https://github.com/w3c/transitions/issues/338#issuecomment-850636248

This specification was originally developed in levels, Level 2 is a W3C Recommendation.
Level 3 as WD introduced Ability to execute marks and measures across arbitrary timestamps
and Support for reporting arbitrary metadata along with marks and measures. The WG wishes to 
drop levels, merge with the existing recommendation and use the process2020 living standard model.

  - Explainer¹ (minimally containing user needs and example code): giving the history of this spec, its scope is hopefully well-understood at this point. From the Director's comment in the CR transition request, it seems that only recent additions would eventually need a review.
  - Specification URL: https://w3c.github.io/user-timing/
  - Tests: [wpt folder(s), if available] https://wpt.fyi/results/user-timing
  - Security and Privacy self-review²: https://w3c.github.io/perf-security-privacy/#privacy-and-security-considerations
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/user-timing/issues
  - Primary contacts (and their relationship to the specification): @yoavweiss, @caribouW3
  - Organization(s)/project(s) driving the specification:  WebPerf WG

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

  💬 leave review feedback as a **comment in this issue** and @-notify [github usernames] 

Thank you!

**Comment by torgo** [comment]
Hi @caribouW3 can you please give us a bit more context on this review - specifically you mention that there have been "recent additions" that would require a re-review but can you please be specific about what those additions are and what kind of feedback you're seeking from the TAG on these?

**Comment by caribouW3** [comment]
Hi!
The additions were brought with level 3 in comparison to the level 2 REC (support for Web Workers and some
processing clarifications) and they were reviewed in FPWD (https://lists.w3.org/Archives/Public/public-review-announce/2019Mar/0000.html)

Since then, there's not been significant changes:
diff between FPWD and latest published draft: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2F2019%2FWD-user-timing-3-20190305%2F&doc2=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FWD-user-timing-3-20210308%2F

This new wide review has been requested as part of CR transition w3c/transitions#338

**Comment by cynthia** [comment]
In 3.2.1.8, something that was previously assigned null is changed to something else - is this intentional? It seems like the structured deserialize procedure described here doesn't seem to set anything to null. (unless I'm missing something)

https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize

**Comment by yoavweiss** [comment]
You're talking about `detail` which is potentially [set to null](https://www.w3.org/TR/user-timing-3/#:~:text=Otherwise%2C%20set%20it%20to%20null) (in 3.1.3.9.2)?
If so, my read is that [serialize](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal) returns a `{ [[Type]]: "primitive", [[Value]]: null }` and then [deserialize](https://html.spec.whatwg.org/multipage/structured-data.html#structureddeserialize) sets the value to null in step 5.

At the same time, we could add a null check here if it makes things more readable.

**Comment by cynthia** [comment]
Ah, I see. Makes sense now - think adding a null check would make it readable. (and better conveys expectations) Thanks for the quick response!

**Comment by cynthia** [comment]
Based on @yoavweiss's update, we are happy with the change and think this is safe to close. Thanks for bringing this to our attention.
