### ISSUE TITLE
Capability Delegation

### ISSUE THREAD

**Issue by mustaqahmed** [w3ctag/design-reviews#655]
Ya ya yawm TAG!

I'm requesting a TAG review of Capability Delegation.

"Capability delegation" means allowing a frame to relinquish its ability to call a restricted API and transfer the ability to another (sub)frame it trusts. The focus here is a dynamic delegation mechanism which exposes the capability to the target frame in a time-constrained manner (unlike `<iframe allow=...>` attribute which is not time-constrained).

  - Explainer: https://wicg.github.io/capability-delegation/
  - Specification URL: https://wicg.github.io/capability-delegation/spec.html
  - Tests: Not available yet.
  - Security and Privacy self-review: https://github.com/WICG/capability-delegation/blob/main/security_and_privacy_questionnaire.md
  - GitHub repo: [WICG/capability-delegation](https://github.com/WICG/capability-delegation)
  - Primary contacts (and their relationship to the specification):
      - Mustaq Ahmed (@mustaqahmed), Google
  - Organization(s)/project(s) driving the specification: Google Chrome
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - Stripe publicly supported this proposal [in the WICG discourse thread](https://discourse.wicg.io/t/capability-delegation/4821/3).
      - Web Payments [spec issue](https://github.com/w3c/payment-request/issues/917).
      - A comment from HTML editor about fixing a [Screen Capture issue](https://github.com/w3c/mediacapture-screen-share/issues/167#issuecomment-821290060).
      - This proposal also addresses concerns raised in [this related TAG review](https://github.com/w3ctag/design-reviews/issues/347#issuecomment-529793544).
  - External status/issue trackers for this specification: https://www.chromestatus.com/feature/5708770829139968

Further details:

  - [X] I have reviewed the TAG's [Web Platform Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: 
  - The group where the work on this specification is currently being done: WICG
  - The group where standardization of this work is intended to be done: WHATWG and Web Payments
  - Major unresolved issues with or opposition to this specification: None so far
  - This work is being funded by: Google Chrome

You should also know that our [previous TAG request](https://github.com/w3ctag/design-reviews/issues/347) to delegate user activation raised valid concerns about being too generic, so we limited the scope of delegation here to a particular API.  More details can be found in [this section](https://docs.google.com/document/d/1IYN0mVy7yi4Afnm2Y0uda0JH8L2KwLgaBqsMVLMYXtk/edit#bookmark=id.2pydwea2nh99) in the design doc.

We'd prefer the TAG provide feedback as:
  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by mustaqahmed** [comment]
We are hoping to start a Chrome Origin Trial with Stripe as a partner by the end of August.  We would really appreciate a feedback here to prepare for that, even if it is just a preliminary feedback.  Thanks!

**Comment by hadleybeeman** [comment]
Hi @mustaqahmed. We are looking at this in our [TAG breakout](https://github.com/w3ctag/meetings/blob/gh-pages/2021/telcons/08-16-agenda.md). 

We were wondering: Can advertisers ask top-level sites to give them this permission, and get more control than they have now? We already have the potential for a similar issue when advertisers ask the top-level site to run their ad script, but would your proposed API make the situation more confusing for users?

**Comment by flackr** [comment]
Hi @hadleybeeman. It's true that advertisers could now ask top-level sites to delegate them a capability instead of just requiring their ad script to run (which gives them arbitrary permissions). However, the ability of top-level sites to delegate the capability is ephemeral both in when it can be done and how long it can be used.

1. It can only be done when the top-level site has user activation (e.g. click). This means the ad-frame could not expect to have the capability at any arbitrary time which would make it difficult to enforce (i.e. the ad-frame wouldn't know whether it doesn't have the capability because the host site didn't grant it, or because the host site didn't get an activation for it yet).
2. The capability itself is very short-lived. When granted the ad-frame can only use it for a very short window of time.

Additionally, the specific capability is explicitly granted so it is easier to audit than ad-script.

**Comment by torgo** [comment]
Hi @mustaqahmed @flackr we're discussing in this week's TAG breakouts. is there anything further on multi-implementer support? I note a link to the [Mozilla Standards Position](https://github.com/mozilla/standards-positions/issues/565) and the feedback seems like positive engagement...

**Comment by mustaqahmed** [comment]
We are not aware of any implementation plan by other browsers, but we're actively involved in working through the design with Mozilla (see the [issues](https://github.com/WICG/capability-delegation/issues?q=is%3Aissue) in our repository).

We would appreciate any feedback/comment from TAG, even if they are preliminary.

**Comment by atanassov** [comment]
@cynthia and I reviewed the proposal one more time during our Madripoor vf2f. @mustaqahmed, thank you for acknowledging my feedback about specifying an allow list of standard features, instead of the current normative spec text which implies all standard features.

With these proposed spec changes we are happy to close the review. Thank you for working with us and being receptive to our feedback. We look forward to see more progress done with the WHATWG. Good luck.
