### ISSUE TITLE
`handle_links` manifest field ✨

### ISSUE THREAD

**Issue by diekus** [w3ctag/design-reviews#695]
Hola TAG!

I’m requesting an *early* TAG review of web app link handling. 

When clicking on a link, the default behavior is that the browser will open and navigate to the specified URL. However, if a compatible application is installed, a user might prefer to have that application launch and "open" said link. This is the case for native apps that range from media consumption to productivity, where if installed, will open when clicking on a link with related content. This is generally the preferred way to interact with the referenced content. To achieve this, an installed application might want to register itself to handle links and create this seamless flow. From a UX perspective, it is desirable to give users choice on how they prefer the link to be opened, and it is important since it creates the cohesive and integrated experience mentioned previously.

- Explainer: https://github.com/WICG/pwa-url-handler/blob/main/handle_links/explainer.md
- Security and Privacy self-review: https://raw.githubusercontent.com/WICG/pwa-url-handler/main/handle_links/Security%20and%20Privacy%20Self-Review%20Questionnaire.md
- Primary contacts: 
  - Diego Gonzalez (@diekus), Microsoft
  - Lu Huang (@luhuangmsft), Microsoft
  - Mandy Chen (@mandymsft), Microsoft
- Organization/project driving the design: Microsoft
- External status/issue trackers for this feature (publicly visible, e.g. Chrome Status): https://chromestatus.com/feature/5740751225880576

Further details:
- [ x ] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
- The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
- The group where standardization of this work is intended to be done ("unknown" if not known): unknown
- Existing major pieces of multi-stakeholder review or discussion of this design: 
- Major unresolved issues with or opposition to this design: N/A
- This work is being funded by: Microsoft

You should also know that this work is the evolution of the URL Handling feature. We have iterated on the idea of how URL handling should work on installed web apps, creating a clearer separation of roles between `handle_links` and `scope_extensions `. 

The explainer to the previous “shape” of this feature is listed here: https://github.com/WICG/pwa-url-handler/blob/main/explainer.md. 

The TAG review for the previous “shape” of this feature is: https://github.com/w3ctag/design-reviews/issues/552 .

Related APIs: `scope_extensions`: https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md

We'd prefer the TAG provide feedback as:
💬 leave review feedback as a comment in this issue and @-notify : @diekus, @luhuang

✨

**Comment by etnos** [comment]
Hi @diekus and @luhuang !

Please answer these questions to help us better understand the proposal. 

1. After a PWA is installed, is it possible to change the handle_links mode? E.g., the mode is set to "all" and at some point, I want to set it to "none" or "auto". 

2. Is it a new behavior or it is possible to achieve it via SW?

Thanks!

**Comment by LuHuangMSFT** [comment]
Hi @etnos 

> 1. After a PWA is installed, is it possible to change the handle_links mode? E.g., the mode is set to "all" and at some point, I want to set it to "none" or "auto".

`handle_links` should be treated as a hint or suggestion from the app to the UA. As such, it's not something that the end user needs to interact with directly. The UA may implement link handling settings for apps that the end user can control. Those settings need not correspond 1-1 with these options. 

For our first implementation, we intend to use `handle_links` to decide the initial setting for an app after install. These settings may look like: [handle link in app client directly | prompt user to handle link in app | never handle link in app].  Afterwards, the user may override this setting.

> 2. Is it a new behavior or it is possible to achieve it via SW?

This is a new behavior. There is no previous behavior that captures the same information from the app to the UA. It should not be achieved with a service worker because 1. it is a declarative API suited to the manifest, 2. it is not expected to change often or depend on other state, and 3. it is useful even when no SW is found.

**Comment by cynthia** [comment]
> The user interacts with the setting of the installed app and not the hint from the app.
This is a bit unclear - does this assume that the user agent provide a mechanism to set this?

> Afterwards, the user may override this setting.
Could you clarify if this is something that the application is expected to provide or the user agent? What happens if the application decides to not provide a way to set this?

**Comment by cynthia** [comment]
See also: https://github.com/WICG/pwa-url-handler/issues/42

**Comment by torgo** [comment]
Hi @diekus have you achieved any clarity on where this might end up after WICG? Maybe Web Applications working group?

**Comment by torgo** [comment]
Hi @diekus @LuHuangMSFT we're just reviewing today at our F2F. We're largely happy with the initial proposal. We're slightly concerned about the possibility that the user might get an unexpected user experience - and to what the balance should be between user choice and author choice. Overall we would like to see how this experiment turns out so we would appreciate the opportunity to re-review with some early implementation feedback. ✨
