### ISSUE TITLE
FedCM Auto Re-authentication API

### ISSUE THREAD

**Issue by yi-gu** [w3ctag/design-reviews#813]
Wotcher TAG!

I'm requesting a TAG review of FedCM Auto Re-authentication API .

An extension to the existing [FedCM API](https://fedidcg.github.io/FedCM/) that provides a streamlined UX when users return to websites. The API requires that the user has already granted permission for the RelyingParty (RP) and Identity Provider (IdP) communication in the browser through a previous FedCM call.

  - Explainer¹ (minimally containing user needs and example code): [[url](https://github.com/fedidcg/FedCM/issues/429)]
  - Security and Privacy self-review²: [[url](https://github.com/fedidcg/FedCM/issues/429#:~:text=Privacy%20Consideration)]
  - GitHub repo (if you prefer feedback filed there): [[url](https://github.com/fedidcg/FedCM)]
  - Primary contacts (and their relationship to the specification):
      - [Yi Gu] (@yi-gu), Google
      - [Sam Goto] (@samuelgoto), Google, spec editor
  - Organization/project driving the design: [Google Chrome / FedCM]
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
     - [Chrome Status](https://chromestatus.com/feature/5108344837111808)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): FedID CG
  - The group where standardization of this work is intended to be done ("unknown" if not known): unknown
  - Existing major pieces of multi-stakeholder review or discussion of this design: N/A
  - Major unresolved issues with or opposition to this design: N/A
  - This work is being funded by: Google Chrome
  
You should also know that the initial FedCM TAG review is https://github.com/w3ctag/design-reviews/issues/718. We're requesting a review specifically on the addition: auto re-authentication.

We'd prefer the TAG provide feedback as (please delete all but the desired option):
  💬 leave review feedback as a **comment in this issue** and @-notify @yi-gu

**Comment by hadleybeeman** [comment]
Hi @yi-gu. Thanks for opening this review. If you'd like our feedback, could you please draft us a quick explainer to cover how you'd like this to work and what other approaches you've considered?

If it helps, our [explainer template](https://github.com/w3ctag/tag.w3.org/blob/main/explainers/template.md) and [explainer explainer](https://tag.w3.org/explainers/) are posted. 

We look forward to hearing more from you.

**Comment by samuelgoto** [comment]
Hey @hadleybeeman thanks for reviewing this! I replied to @torgo over email, but figured it would be useful to give context here more publicly in case we run into this again.

> Hi @yi-gu. Thanks for opening this review. If you'd like our feedback, could you please draft us a quick explainer to cover how you'd like this to work and why you've chosen that approach above the other approaches you've considered?
> If it helps, our [explainer template](https://github.com/w3ctag/tag.w3.org/blob/main/explainers/template.md) and [explainer explainer](https://tag.w3.org/explainers/) are posted.

We did originally have proposals to extend FedCM in the form of explainers that follow the template (you can still see some of them [here](https://github.com/fedidcg/FedCM/tree/main/proposals)), but we got feedback from Mozilla that it would help their reviews if these were filed as github Issues as opposed to standalone markdown files: making comments in github issues is a much lower hurdle to pay to engage than it is to kick off new github issues or submit pull requests.

> file issues followed by proposals followed by spec PRs, as opposed to explainers, to substantially decrease the cost of engagement (much easier to comment on github issues than to comment on explainers)

https://github.com/fedidcg/FedCM/issues/431#issuecomment-1425025469

That overall makes sense to us (we'll follow whatever makes our reviewers life easier), so we started to slowly port our explainers into github issues.

So, what @yi-gu pointed you to in the TAG request [here](https://github.com/fedidcg/FedCM/issues/429#issuecomment-1424282049) is, in fact, the place in which we explain the problem, the alternatives we considered and the proposal we have an inclination to go for.

I'm sorry if this causes extra work for you all, and we'd be happy to adapt to find ways to make reviews (mozilla's and yours included) as effective as possible, but just wanted to give context as to why these aren't standalone markdown files.

Since we do expect to send you all a few more reviews in the next few weeks/months, let me know if you feel like this isn't a reasonable format and we can work together with Mozilla to figure out something that works, Sam.

**Comment by plinss** [comment]
@maxpassion and I looked at this during our Tokyo F2F. One question that came up is about getting user consent for the re-auth flow. It seems like in addition to the RP opting-in to this flow, perhaps the user should also have the option to (or be required to) opt-in during the initial login flow. e.g. when prompted for intiial permissions have to choice of 'Remember me' or 'Only for this session' or such. Our concern is if a user uses FedCM to log in to a service on a public terminal, would the next person using the same terminal be able to sign back in to the original service without knowing the user's credentials? (or at least gain some knowledge about the previous user having an account on the service and possibly login name.)

**Comment by yi-gu** [comment]
Hello again!

We have finalized our proposal to support auto re-authentication. As mentioned earlier, we decided to reuse the existing [mediation requirements](https://w3c.github.io/webappsec-credential-management/#mediation-requirements) and [preventSilentAccess](https://w3c.github.io/webappsec-credential-management/#dom-credentialscontainer-preventsilentaccess) from the CredentialManagement API. i.e. no new web API will be introduced for this feature.

The spec PR has been merged after we [aligned with](https://github.com/fedidcg/FedCM/pull/458#issuecomment-1539631816) Firefox on the proposal.

Since there's no new API, should we close this review? Please let us know if anything else is needed from us.

Thank you!

**Comment by torgo** [comment]
Given the above info we're happy to close. As Peter commented above, we generally remain concerned about scenarios involving public terminals so we encourage you to take those into account. Thanks!  ✨
