### ISSUE TITLE
Web of Things (WoT) Profile - Review Requested

### ISSUE THREAD

**Issue by mmccool** [w3ctag/design-reviews#818]
こんにちは TAG-さん!

I'm requesting a TAG review of Web of Things (WoT) Profiles.

The WoT Profile [WoT Profile](https://w3c.github.io/wot-profile/) defines a Profiling Mechanism which restricts options and guides best practices to enable out-of-the-box interoperability when using Web of Things for greenfield devices.  The current draft defines only profiles for HTTP.  Out-of-the-box interoperability implies that devices can be integrated together into various application scenarios without deep level adaptations.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/wot-profile/blob/main/explainer/Explainer.md
  - Specification URL: https://www.w3.org/TR/2023/WD-wot-profile-20230118/
  - Tests: WPT tests are not applicable as this specification is not for browser functionality.  However, we are tracking feature implementations from multiple contributors and a draft test report is available here: https://github.com/w3c/wot-profile/blob/main/testing/report.html
  - User research: The restrictions proposed in Profiles are based on best practices observed during testing of the WoT Thing Description 1.1 specification.  Test results for that specification are located here: https://github.com/w3c/wot-thing-description/blob/main/testing/report11.html
  - Security and Privacy self-review²: https://github.com/w3c/wot-architecture/blob/main/publication/ver11/security_and_privacy.md (single review for all WoT deliverables in this charter)
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/wot-profile
  - Primary contacts (and their relationship to the specification):
      - Michael McCool (@mmccool), Intel Corp.
      - Michael Lagally (@mlagally), Oracle Corp.
      - Sebastian Kaebisch (@sebastiankb), Siemens AG
      - Ben Francis (@benfrancis), Invited Expert
      - Ryuichi Matsukura (@mryuichi ), Fujitsu Ltd.
      - Tomoaki Mizushima, (@chachamimm), Internet Research Institute, Inc.
  - Organization(s)/project(s) driving the specification: Various
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Aiming for CR transition by 2023-03-30
  - The group where the work on this specification is currently being done: Web of Things (WoT) WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification: Expect async actions to still be at risk going into CR.
  - This work is being funded by:

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  🐛 open issues in our GitHub repo for **each point of feedback**

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://tag.w3.org/explainers/). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

**Comment by hadleybeeman** [comment]
Hello, @mmccool! Thanks for opening this issue, and apologies that it has taken us a while to get to this. 

We are looking at this now. How are you doing with take-up and implementations?

Also, we have noticed that [Matter](https://en.wikipedia.org/wiki/Matter_(standard) is gaining traction. Does the WoT profile play with other initiatives like this, or are they completely unrelated?

**Comment by benfrancis** [comment]
> Also, we have noticed that [Matter](https://en.wikipedia.org/wiki/Matter_(standard)) is gaining traction. Does the WoT profile play with other initiatives like this, or are they completely unrelated?

I will defer to @mmccool on the overall implementation status, but perhaps as an editor of the WoT Profiles specification I can provide some input on this specific point.

Matter is certainly an interesting new standard, particularly in the consumer smart home space, due to its cross-vendor support. After several years of marketing, commercial products are finally starting to trickle onto the market, and whilst Matter is not yet quite living up to its interoperability promises it is certainly a welcome development in that space.

However, Matter is just one of a very large number of different protocols in what remains a very heterogeneous Internet of Things, with a [wide range of protocols](https://www.emnify.com/iot-glossary/guide-iot-protocols) at [various layers](https://en.wikipedia.org/wiki/Internet_of_things#Comparison_of_technologies_by_layer) of the networking stack used for different [use cases](https://w3c.github.io/wot-usecases/#sec-horizontal-ucs) and [application domains](https://w3c.github.io/wot-usecases/#sec-vertical-ucs). I would suggest that the Web of Things should not be seen as a competitor to those protocols, but rather a bridge between them.

There are two ways a Matter device might be integrated with the Web of Things:
1. By describing a Matter device directly using a [Thing Description](https://www.w3.org/TR/wot-thing-description11/) via a Matter [binding specification](https://w3c.github.io/wot-binding-templates/), for which a [liason](https://w3c.github.io/wot-charter-drafts/wot-wg-2023-draft.html#external-coordination) with the Connectivity Standards Alliance has been proposed for the next charter
2. By bridging Matter devices on a local network to the Web of Things on the Internet, using an IoT gateway which exposes the device using a common web protocol which can be directly consumed by web services

The latter is where I think the current WoT Profiles specification comes in, and is the approach taken by my [company's](https://krellian.com/) own Web of Things [gateway](https://krellian.com/products/hub/) [implementation](https://github.com/WebThingsIO/gateway/) (which bridges a large number of different IoT protocols to the Web of Things) and [cloud service](https://krellian.com/services/cloud/) (which consumes devices using that standardised interface).

I hope that helps, but I am happy to answer any follow-up questions if I can.

**Comment by plinss** [comment]
The TAG would like to invite a handful of representatives from the WoT WG to join us for a session to help us get a better understanding of some of the goals and plans of the WG. We're hoping that a direct conversation will be more productive than a series of back and forth messages.

We can be a bit flexible around time zones, but out ideal would be in our normal Monday breakout slot from 16:00-17:00 UTC (9-10am Pacific) on any week that works for you (probably after May 29 as that's a US holiday).

**Comment by mmccool** [comment]
Sorry for the late response on this, since we decided not to try and push Profiles through in this charter (ending in a month) our focus has been on the three other WoT documents entering PR.  However, Profiles are included in our next draft charter and it would be a good time to gather input on them.   Are your constraints on a meeting time the same?  I will check with others involved in Profiles about whether the Monday slot works.

As for Matter, what Ben said.  My company is a member of the consortium and I have worked with Matter a fair bit.  While technically the standard solves several problems related to security and performance, it's not going to magically replace all the existing standards overnight, nor is is completely suitable for all use cases, being mostly focused on Smart Home.  The statements they make about it solving problems of interoperability are mostly in that specific context and based on assumptions about wide adoption there.  My expectations is that Matter will slowly gain traction but that IoT will continue to use a variety of standards and WoT will remain relevant.

**Comment by mmccool** [comment]
I unfortunately won't be there in person, so best to arrange any F2F with @sebastiankb

**Comment by rhiaro** [comment]
Hi again @mmccool and @sebastiankb We're really sorry we didn't manage to arrange a time to meet with you at TPAC. We're going to close this for now, please could you file a new review request at a suitable time during your next charter period? We unfortunately don't have time for an early review of this at the moment, but will do our best to get back to you if we do managed to clear our backlog a bit more before we hear from you next.
