### ISSUE TITLE
Tabbed web apps

### ISSUE THREAD

**Issue by loubrett** [w3ctag/design-reviews#841]
こんにちは TAG-さん!

I'm requesting a TAG review of tabbed web apps.

Currently PWAs in a standalone window can only have one page open at a time. Some apps expect users to have many pages open at once. Tabbed mode adds a tab strip to standalone web apps that allows multiple tabs to be open at once.
This feature includes a new display mode `tabbed` and a new manifest member `tab_strip` which let apps enable the tab strip and customize it.

  - Explainer: https://github.com/WICG/manifest-incubations/blob/gh-pages/tabbed-mode-explainer.md
  - User research: N/A
  - Security and Privacy self-review²: [Tabbed web apps: Security and Privacy self-review](https://docs.google.com/document/d/1aSfJos5lBvC5ykh50OIjRmXn9tnjC426EKiVDQ8GvyQ/edit?usp=sharing)
  - GitHub repo (if you prefer feedback filed there): https://github.com/WICG/manifest-incubations/
  - Primary contacts (and their relationship to the specification):
      - Louise Brett (@loubrett), Google
      - Alan Cutter (@alancutter), Google
  - Organization/project driving the design: Google
  - External status/issue trackers for this feature: https://chromestatus.com/feature/5128143454076928

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known): WICG
  - Existing major pieces of multi-stakeholder review or discussion of this design:
  - Major unresolved issues with or opposition to this design:
  - This work is being funded by: Google

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify loubrett

**Comment by torgo** [comment]
Hi @loubrett can you clarify for us: is this intended to be "desktop only"? Is there any thought to how this would work in mobile cases?

**Comment by torgo** [comment]
Other questions that came up in our discussion:  browsers have fairly elaborate tabbing capabilities.. the use cases described are pretty simplistic... what about tab groups?  browsers go to a great extent to differentiate on tab behaviour.  What about tab tearing?  What happens when you have 2 windows and you pull one tab to another?   Or if you pull a tab from an "app" window to browser window? Has any of this been discussed with the use cases you're considering?

**Comment by loubrett** [comment]
Yes this is intended to be desktop only - I'm not sure how it would work on mobile.

It would be up to each browser to decide which tabbing capabilities to enable for web apps and how to handle dragging tabs between windows.

**Comment by LeaVerou** [comment]
Hi there @loubrett,

We're discussing in today's TAG virtual f2f session – we're concerned about "desktop only".  Most available statistics indicate that the majority of web usage is on mobile devices - e.g. see [this run-down of recent access stats for gov.uk web sites](https://hachyderm.io/@TheRealNooshu/109947378812496228) - indicating 58.26% mobile, 39.82% desktop. Also since the web is [multi-browser, multi-OS and multi-device](https://www.w3.org/TR/ethical-web-principles/#multi), we'd like to encourage you to consider mobile and other platforms. We're also concerned about implementation issues across different OSs, @hober will follow up with more details.

We'd like to see more use cases & more discussion of user needs. Even in our short vF2F discussion several different use cases were brought up (Google Maps, microblogging client, Wikipedia etc). We would hate to see a web feature designed for just one thing when it could help meet a lot of different needs. See our relevant [Design Principles discussion](https://github.com/w3ctag/design-principles/issues/450). Also, have you considered the user experience when URLs to this web app are clicked across the OS? (e.g. in a Google Maps PWA, what happens when I click on the pin a friend sent me on Messenger?)

Are you thinking that tabs would only be allowed from the same origin that is the origin of the webapp itself? We're concerned about the user experience of a web app that includes links to other external sites which might then be opened as tabs in the tabbed webapp vs being opened in the user's default browser / browser experience. Equally, saying "you can only open links from the same origin" would be a very different feature, from a user's point of view. What was your intention on this?

**Comment by loubrett** [comment]
> We're discussing in today's TAG virtual f2f session – we're concerned about "desktop only". Most available statistics indicate that the majority of web usage is on mobile devices - e.g. see [this run-down of recent access stats for gov.uk web sites](https://hachyderm.io/@TheRealNooshu/109947378812496228) - indicating 58.26% mobile, 39.82% desktop. Also since the web is [multi-browser, multi-OS and multi-device](https://www.w3.org/TR/ethical-web-principles/#multi), we'd like to encourage you to consider mobile and other platforms. We're also concerned about implementation issues across different OSs, @hober will follow up with more details.

This is a fair point. There’s no reason why it couldn’t work on mobile so it doesn’t need to be desktop only, we have just seen more requests for it on desktop, so that is what we implemented first. There would need to be more thought put into the tab UI on mobile, but that would be up to each implementation and I guess it could work the same as browser tabs on mobile.

> We'd like to see more use cases & more discussion of user needs. Even in our short vF2F discussion several different use cases were brought up (Google Maps, microblogging client, Wikipedia etc). We would hate to see a web feature designed for just one thing when it could help meet a lot of different needs. See our relevant https://github.com/w3ctag/design-principles/issues/450.

I’ve fleshed out the use cases a bit in the explainer.

> Also, have you considered the user experience when URLs to this web app are clicked across the OS? (e.g. in a Google Maps PWA, what happens when I click on the pin a friend sent me on Messenger?)

This is related to the launch handler API. I’ve added a section to the explainer about how these two interact (TLDR: the app could handle the links, causing them to open in a new app tab).

> Are you thinking that tabs would only be allowed from the same origin that is the origin of the webapp itself? We're concerned about the user experience of a web app that includes links to other external sites which might then be opened as tabs in the tabbed webapp vs being opened in the user's default browser / browser experience. Equally, saying "you can only open links from the same origin" would be a very different feature, from a user's point of view. What was your intention on this?

This would be up to each implementation, and it doesn’t necessarily need to be different for tabbed apps vs other web apps. For example in Chrome we have the CCT when an app navigates out of scope, so that currently behaves the same with a tabbed app.

**Comment by hober** [comment]
Hi,
  
@torgo, @leaverou, @matatk, and I took a look at this during our F2F today, and it's unclear why tabs-for-PWAs need any author opt-in at all. If a browser wants to enable Cmd/Ctrl-clicking in a PWA to open in a tab in the PWA window, or for `<a target=_blank href>` to do so, there's nothing stopping them from doing so today. (And it may be worth filing feature requests on the browsers so that they consider doing so.) The existing display mode values are possibly sufficient to control this. For instance, the `fullscreen` display mode probably shouldn't get such tabs.
  
If the concern is that only links that are still within the PWA should open in tabs, and links to outside the PWA should open in the system browser, the browser already has all the information it needs to enable that behavior by default.
  
It might be worth pursuing a more limited feature proposal for simply supplying a URL other than the app's root URL for use when the new tab button is activated.

It's entirely possible we've missed some other justification for having an explicit author opt-in here that goes beyond the existing Web App Manifest feature set. If we have, please let us know, and we'll reopen the review.

**Comment by tomayac** [comment]
Thanks for the review!

- This proposes a number of additions to the Web App Manifest, see the [code snippet in the article](https://developer.chrome.com/docs/capabilities/tabbed-application-mode#complete_example) for a concrete example. 
- There's also some [interaction with the Launch Handler API](https://developer.chrome.com/docs/capabilities/tabbed-application-mode#interaction_with_the_launch_handler_api) (this was TAG-reviewed as https://github.com/w3ctag/design-reviews/issues/683).
- [Feature detection](https://developer.chrome.com/docs/capabilities/tabbed-application-mode#detecting_tabbed_application_mode) happens through a new `display-mode` CSS media feature value.  
- The [demo](https://developer.chrome.com/docs/capabilities/tabbed-application-mode#demo) showcases how the various components are meant to play together.

**Comment by mgiuca** [comment]
Hi @hober and TAG reviewers.

Thanks for your considered review.

If I could rephrase the review feedback so I'm clear I understand it: you are saying that this is a potentially useful feature that the browser could offer, but don't see why it needs to be declared in the manifest or requested by the developer. Why not have (as either an always-on or user-opt-in browser feature) all `display: standalone` apps get tabs in their tab strip?

While that is a position we could take, it seems to unnecessarily limit developer control over their own app experience (in a way that doesn't really empower users). There are good reasons for one app to want a tabbed experience while another does not. For example, a game almost certainly would not want a tabbed experience, while a document editor probably would. This is a decision that apps on native app platforms can make for themselves (e.g. on Windows or macOS, there is no system-wide "all apps must be tabbed" UI treatment, yet individual apps can provide a tabbed document experience). The goal is to empower developers to deliver the best experience to their users for their particular use case.

You could make the same claim about any other display mode: "why should the developer get to choose between `minimal-ui` vs `standalone`, shouldn't the browser force a consistent treatment or let the user choose?" The answer is the same: the developer knows what is the best way to frame their app. (Of course, on the web platform, this sentiment does not extend to letting the developer take any harmful actions against the user, but that is not the case here.)

Does the above warrant re-examination by the TAG or would you still consider this issue closed?

Regards

Matt

**Comment by mgiuca** [comment]
Hi TAG,

Just giving this thread some updates on the developments on tabbed mode since February.

Acknowledging that TAG resolved this as "unsatisfied" based on not seeing a lot of value in the feature. We have posted additional justification above, and in the meantime, have pushed ahead with the feature.

* Tabbed Mode is [shipping in Chrome 126](https://groups.google.com/a/chromium.org/g/blink-dev/c/L6AfXU0-GOc/m/Y4SRkKUPAQAJ). At the present time, it will be ChromeOS only (see the discussion in that thread - this is due to resourcing, and we have noted that in principle this API can be applicable on all platforms).
* We have produced a comprehensive spec, currently incubating in the [manifest-incubations](https://wicg.github.io/manifest-incubations) repository. Here are direct spec links for the new [tabbed display mode](https://wicg.github.io/manifest-incubations/#dfn-tabbed) and the [tab_strip manifest member](https://wicg.github.io/manifest-incubations/#tab_strip-member).
* Tabbed mode was featured in the ChromeOS developer talk at [Google I/O last week](https://chromeos.dev/en/posts/io-2024#introducing-tabbed-pwa-mode). To coincide with this, [Figma](https://figma.com/) launched a PWA which works with tabbed mode on ChromeOS. There was some [press coverage](https://chromeunboxed.com/tabbed-pwas-for-chromebooks-will-be-a-game-changer-web-apps/) as well.

Cheers

Matt
