### ISSUE TITLE
Bluetooth RFCOMM in Web Serial API

### ISSUE THREAD

**Issue by nondebug** [w3ctag/design-reviews#854]
こんにちは TAG-さん!

I'm requesting a TAG review of Bluetooth RFCOMM in Web Serial API.

The Bluetooth RFCOMM (Radio frequency communication) protocol provides emulated RS-232 serial ports. This feature would enable applications to make connections to RFCOMM services on paired Bluetooth Classic devices using the Web Serial API.

  - Explainer: https://github.com/WICG/serial/blob/main/EXPLAINER_BLUETOOTH.md
  - Specification URL: https://wicg.github.io/serial/
  - Tests: In progress
  - User research: N/A
  - Security and Privacy self-review: https://github.com/WICG/serial/blob/main/security-privacy-questionnaire-bluetooth-rfcomm.md
  - GitHub repo (if you prefer feedback filed there): File feedback on this issue
  - Primary contacts (and their relationship to the specification):
      - Matt Reynolds (@nondebug, Google Chrome)
  - Organization(s)/project(s) driving the specification: Google Chrome
  - Key pieces of existing multi-stakeholder review or discussion of this specification:
      - Gecko: Negative signals (https://github.com/mozilla/standards-positions/issues/336 https://github.com/mozilla/standards-positions/issues/687)
      - WebKit: Negative signals (https://webkit.org/tracking-prevention/ https://github.com/WebKit/standards-positions/issues/199)
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): [Chrome Status: Web Serial support for Bluetooth RFCOMM services](https://chromestatus.com/feature/5686596809523200)

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: We expect to start an experiment with this feature in Chrome 116
  - The group where the work on this specification is currently being done: WICG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): Device & Sensors Working Group
  - Major unresolved issues with or opposition to this specification:
      - Apple and Mozilla are both opposed to Web Serial API
  - This work is being funded by: Google Chrome

You should also know that...

The feature can be enabled in Chrome 116 with the flag chrome://enable-bluetooth-spp-in-serial-api.

We'd prefer the TAG provide feedback as (please delete all but the desired option):

  💬 leave review feedback as a **comment in this issue** and @-notify @nondebug

**Comment by cynthia** [comment]
We discussed this during our vF2F today - we can see the appeal of WebSerial (at least the somewhat niche use cases where it could be useful), but had a hard time coming up with a compelling user story where this would get mass adoption. What would be a use case (that is appealing to a reasonably large group of users)?

**Comment by tomayac** [comment]
> We discussed this during our vF2F today - we can see the appeal of WebSerial (at least the somewhat niche use cases where it could be useful), but had a hard time coming up with a compelling user story where this would get mass adoption. What would be a use case (that is appealing to a reasonably large group of users)?

Would [LEGO® using this API in their kits](https://developer.chrome.com/blog/lego-education-spike-web-bluetooth-web-serial/#web-serial-api-connection) count as "compelling user story where this would get mass adoption"?

**Comment by maxpassion** [comment]
> > We discussed this during our vF2F today - we can see the appeal of WebSerial (at least the somewhat niche use cases where it could be useful), but had a hard time coming up with a compelling user story where this would get mass adoption. What would be a use case (that is appealing to a reasonably large group of users)?
> 
> Would [LEGO® using this API in their kits](https://developer.chrome.com/blog/lego-education-spike-web-bluetooth-web-serial/#web-serial-api-connection) count as "compelling user story where this would get mass adoption"?

Hi @tomayac, in this use case, the Web Serial API is used when connected via USB? If so, it seems did not justify why Serial via Bluetooth is needed.

**Comment by scheib** [comment]
Re cynthia, maxpassion: "compelling user story where this would get mass adoption": I've already seen this by walking into a school and seeing https://vex.com robotics being used - they're [used widely](https://www.vexrobotics.com/competition). Google also showcased the similar https://spike.legoeducation.com/ this year at Google IO & Connect events. 

People expect computing technology to work, even if infrequently.  Serial has a variety of applications from education, home automation, enterprise/industrial, maker, and common consumer devices. These range from frequent daily use (e.g. point of sale devices, inventory tools, industrial sensors) to infrequent (e.g. configuration of consumer devices).

In the TPAC 2022 Breakout session Device APIs (Bluetooth, HID, Serial, USB) [slides](http://goo.gle/tpac2022-device-apis)[ (PDF copy)](https://lists.w3.org/Archives/Public/www-archive/2022Sep/att-0017/device-apis.pdf) I discuss the adoption at a larger scale. In the year since that presentation Serial usage has peaked at more than 4 times the usage we'd seen previously.

Bluetooth RFCOMM is a request the Chrome team has had from multiple partners, the top two that come to mind are in education and consumer devices, with weekly and monthly frequency use cases respectively, both from highly recognized global brands.  Their devices already use Bluetooth RFCOMM protocol and they won't be changing the hardware/firmware for these.  For the web to meet the need we are implementing this approach.  The alternative is that developers like these meet the user's needs with e.g. windows apps or fail to meet the needs on Chromebooks.  Even on Windows, partners indicate the high value of e.g. not requiring teachers/children to try to install and manage other applications vs just using the web app.

**Comment by torgo** [comment]
Hi @scheib thanks for that. There's no doubt that communicating with devices, particularly in an educational context as you've elaborated, is a compelling use case for computers.  Clearly, however, there is a difference of opinion amongst implementers about whether web applications should be empowered to make such connections.

We've reviewed the [Web Bluetooth API positively](https://github.com/w3ctag/design-reviews/issues/139).
  
We've also reviewed the [web serial API](https://github.com/w3ctag/design-reviews/issues/431) - for which we recognized the use case but also we expressed concerns about multi-stakeholder support.

Speaking personally, I'm a big supporter of these APIs. I've personally demonstrated Web Bluetooth on stage at developer events.  I fully get it.  However, as TAG I have to acknowledge that the development of these capabilities has not brought other implementers along.
  
Putting aside the multi-stakeholder considerations, we're not clear on some aspects of the user flow and permission model.  The explainer could benefit from spelling out how a device gets connected, how the permissions are requested, etc... ?

**Comment by torgo** [comment]
As reflected in our [minutes from 09-25 week](https://github.com/w3ctag/meetings/blob/gh-pages/2023/telcons/09-25-minutes.md) we are closing this as "satisfied with concerns." We're happy with the design and we understand the user need. We remain concerned about the lack of overall support for the underlying web serial and web bluetooth specs themselves. We'd like to encourage you to do more to builld consensus around these specs with other browsers / browser engine makers.
