### ISSUE TITLE
Add Skip-Ad media session action

### ISSUE THREAD

**Issue by jiajiabingcheng** [w3ctag/design-reviews#957]
こんにちは TAG-さん!

I'm requesting a TAG review of Adding Skip-Ad media session action.

This feature was initially proposed and implemented four years ago but remained disabled due to a lack of practical use cases. It already received LGTM from the Blink dev group back in February 2019. Given our team's plan to implement a feature related to this action, we are now proposing to enable it.

  - Explainer¹ (minimally containing user needs and example code): 
  https://developer.chrome.com/blog/media-updates-in-chrome-73#skipad
  
  - Specification URL: https://www.w3.org/TR/mediasession/#dom-mediasessionaction-skipad
  
  - Tests:   https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/mediasession/setactionhandler.html
  
  - User research: [url to public summary/results of research]
 
  - Security and Privacy self-review²: 
  This new action does not provide any new data to the website. We just add a new media session action for the website to register an action handler for, but does not expose new data to the website. See more in the security and Privacy section in the Chrome Status

  - GitHub repo: 
 N/A
 
  - Primary contacts (and their relationship to the specification):
      Jiaming Cheng (@jiajiabingcheng), Google

  - Organization(s)/project(s) driving the specification: 
    Google, SkipAd

  - Key pieces of existing multi-stakeholder (e.g. developers, implementers, civil society) support, review or discussion of this specification:
    - Chromium comments: [url]
    - Mozilla comments: https://github.com/mozilla/standards-positions/issues/1026
    - WebKit comments: https://github.com/WebKit/standards-positions/issues/350
    - Etc.
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    https://chromestatus.com/feature/4749278882824192?gate=6100738773614592

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: [please provide]
  - The group where the work on this specification is currently being done:
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue):
  - Major unresolved issues with or opposition to this specification:
  - This work is being funded by:

You should also know that...

[please tell us anything you think is relevant to this review]

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://tag.w3.org/explainers/). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

³ For your own organization, you can simply state the organization's position instead of linking to it. Chromium doesn't have a standards-positions repository and [prefers](https://source.chromium.org/chromium/chromium/src/+/main:docs/standards/positions/GoogleChrome/README.md) to use comments from the teams that maintain the relevant area of their codebase.

**Comment by torgo** [comment]
Just a quick note - and noting this is not formal TAG feedback, but a question that came up in our discussion in this morning's breakout call where we discussed this: could this API could be generalized so that it's not specifically referencing advertizing but more the general use case of skipping an intro or skipping "to the main content"? It feels like there are multiple cases where this could be used that are not advertizing related, and also we don't currently have other APis in the platform that are just supporting advertising.

**Comment by martinthomson** [comment]
Along the lines that @torgo mentions, it occurs to me that video services often have the ability to skip an intro sequence.  This fills a similar function, so if you are looking for generality, that might be worth looking into.

**Comment by martinthomson** [comment]
Firstly, we need to ask whether this was implemented in browsers *other than* Chrome.  If it wasn't, this presents an opportunity to improve it.

One desire we have is to make this feature generic, rather than being specific to skipping ads.

We observe that the [Media Chapter](https://github.com/w3ctag/design-reviews/issues/952) information (that we recently reviewed) might provide a useful hook for this sort of control.  "Chapters" that are skippable can be marked as such in that metadata.  The type of thing to skip might be included in that information.  Consider `{ ..., skippable: "ad" }`.  That would allow for skipping of intro sequences and credits in addition to ads.

For accessibility purposes, this sort of thing might need to be given a symbol so that non-textual users are able to more readily access the function.  Please consult an accessibility expert about this (@matatk indicated that APA is likely to want to take another look; it's been a while since they reviewed the original MediaSession proposal).

**Comment by miketaylr** [comment]
> Firstly, we need to ask whether this was implemented in browsers _other than_ Chrome. If it wasn't, this presents an opportunity to improve it.

Looks to be implemented in Gecko for quite some time:

https://searchfox.org/mozilla-central/source/dom/webidl/MediaSession.webidl#16-26
https://bugzilla.mozilla.org/show_bug.cgi?id=1582569

**Comment by chrisn** [comment]
I very much agree with https://github.com/w3ctag/design-reviews/issues/957#issuecomment-2328129458 that a more generic skip action would be useful.

**Comment by martinthomson** [comment]
I just opened https://github.com/w3c/mediasession/issues/340 to track that proposal.

**Comment by matatk** [comment]
Thanks for the review request. As this is shipping in multiple engines, and our concerns have been raised in an issue to be addressed in future, we'll close this review.
