### ISSUE TITLE
Fenced frames with local unpartitioned data access

### ISSUE THREAD

**Issue by shivanigithub** [w3ctag/design-reviews#975]
I'm requesting a TAG review of **Fenced Frames with local unpartitioned data access**.

**Overview of proposal**
There are situations in which it is helpful to personalize content on pages with cross-site data, such as knowing whether a user has an account with a third-party service, whether a user is logged in, displaying the last few digits of a user’s credit card to give them confidence that the check-out process will be seamless, or a personalized sign-in button. These sorts of use cases will be broken by third-party cookie deprecation (3PCD). Fenced frames are a natural fit for such use cases, as they allow for frames with cross-site data to be visually composed within a page of another partition but are generally kept isolated from each other. 
The idea proposed here is to allow fenced frames to have access to the cross-site data stored for the given origin within shared storage. In other words, a payment site could add the user’s payment data to shared storage when the user visits the payment site, and then read it in third-party fenced frames to decorate their payment button. 
Today’s fenced frames prevent direct communication with the embedding page via the web platform, but they have network access, allowing for data joins to occur between colluding servers. Since the fenced frame in this proposal would have unfettered access to user’s cross-site data, we cannot allow it to talk to untrusted networks at all once it has been granted access to cross-site data. Therefore, we require that the fenced frame calls `window.fence.disableUntrustedNetwork()` before it can read from shared storage.
The driving motivation for this variant of fenced frames are customized payment buttons for third-party payment service providers (as discussed in this [issue](https://github.com/WICG/fenced-frame/issues/15)) but this proposal is not restricted to payments and we anticipate many other content personalisation use cases will be found with time.

  - Explainer¹ (minimally containing user needs and example code): [[url]](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md)
  - User research: For the personalized payment button use case: [summary of impact by Google Pay](https://developers.googleblog.com/en/updated-google-pay-button-increases-click-through-rates/), [support from the ecosystem](https://github.com/w3ctag/design-reviews/issues/735#issuecomment-1206075921)
  - Security and Privacy self-review²: see below
  - GitHub repo: [[url]](https://github.com/WICG/fenced-frame/tree/master/explainer)
  - Primary contacts (and their relationship to the specification):
      - Shivani Sharma (@shivanigithub), explainer author
  - Organization/project driving the design: Google, Privacy Sandbox
  - External status/issue trackers for this feature (publicly visible, e.g. Chrome Status):
       - https://github.com/WICG/fenced-frame/issues/15

Further details:

  - [✓ ] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - The group where the incubation/design work on this is being done (or is intended to be done in the future): WICG
  - The group where standardization of this work is intended to be done ("unknown" if not known):  WHATWG HTML Standard
  - Existing major pieces of multi-implementer review or discussion of this design: None yet
  - Major unresolved issues with or opposition to this design: None
  - This work is being funded by: Google Privacy Sandbox

**Security and Privacy questionnaire based on https://www.w3.org/TR/security-privacy-questionnaire/**

1. What information might this feature expose to Web sites or other parties, and for what purposes is that exposure necessary?

    Fenced frames can be viewed as a more private and restricted iframe. Fenced frames with the unpartitioned data access allows it to read unpartitioned data from shared storage to show personalized user information to the user, e.g. personalized payment button as described in the explainer. Existing fenced frames functionality already disables communication from the fenced frame to the embedding context but to access the unpartitioned data, the fenced frame is also required to disable network communications, with exceptions such as private aggregation report as described in the explainer [here](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#why-untrusted-network). 

2. Do features in your specification expose the minimum amount of information necessary to enable their intended uses?

    Yes, see above answer for ways information exposure is minimized.

3. How do the features in your specification deal with personal information, personally-identifiable information (PII), or information derived from them?

    Any unpartitioned data that the fenced frames read, if it contains PII, is not exfiltrated out of the fenced frame. 

4. How do the features in your specification deal with sensitive information?

    Same answer as # 3.

5. Do the features in your specification introduce a new state for an origin that persists across browsing sessions?

    No.

6. Do the features in your specification expose information about the underlying platform to origins?

    No

7. Does this specification allow an origin to send data to the underlying platform?

    No

8. Do features in this specification allow an origin access to sensors on a user’s device

    No

9. What data do the features in this specification expose to an origin? Please also document what data is identical to data exposed by other features, in the same or different contexts.

    Same answer as # 1.

10. Do features in this specification enable new script execution/loading mechanisms?

    No

11. Do features in this specification allow an origin to access other devices?

    No

12. Do features in this specification allow an origin some measure of control over a user agent’s native UI?

    No

13. What temporary identifiers do the features in this specification create or expose to the web?

    None.

14. How does this specification distinguish between behavior in first-party and third-party contexts?

    Fenced frames are always present as embedded frames.  

15. How do the features in this specification work in the context of a browser’s Private Browsing or Incognito mode?

    No difference with a regular mode browser

16. Does this specification have both "Security Considerations" and "Privacy Considerations" sections?

    Yes, [privacy considerations](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#privacy-considerations) and [security considerations](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#security-considerations).

17. Do features in your specification enable origins to downgrade default security protections?

    No

18. How does your feature handle non-"fully active" documents?

Based on https://www.w3.org/TR/design-principles/#support-non-fully-active:

*   There is no user interaction with the fenced frame in a non-fully-active document.
*   There is no cross-document interaction/resource sharing possible (e.g. holding locks) in a fenced frame. 
*   There is no expectation that the unpartitioned data read from within a fenced frame should be available when the document is restored.
19. What should this questionnaire have asked?

    N/A

**Comment by hober** [comment]
Recent discussion on #838 (the overall design review of Fenced Frames) covered the "last 4 digits" payment use case. Would you like us to move discussion of that particular use case to this issue? If so, how would you like us to down-scope issue #838?

**Comment by shivanigithub** [comment]
> Recent discussion on #838 (the overall design review of Fenced Frames) covered the "last 4 digits" payment use case. Would you like us to move discussion of that particular use case to this issue? If so, how would you like us to down-scope issue #838?

Yes I think focusing this issue for "local unpartitioned access" makes sense, since that's an added major functionality on existing fenced frames.
With that, https://github.com/w3ctag/design-reviews/issues/838 can then be scoped to the fenced frame API and its core design pieces, including but not limited to being treated as a separate browsing context, it's navigation using fencedFrameConfig object etc.
PLMK if there are any more clarifications on this, thanks!

**Comment by shivanigithub** [comment]
To give some more context on the 3 fenced frames TAG reviews so far:

These 2 that were created where fenced frames support use cases requiring src which should be hidden from the embedder. Examples of these use cases are [Protected Audience](https://github.com/WICG/fenced-frame/blob/master/explainer/use_cases.md#rendering-ads-via-the-protected-audience-api) and [selectURL](https://github.com/WICG/fenced-frame/blob/master/explainer/use_cases.md#selecting-and-rendering-a-url-based-on-cross-site-data-via-selecturl)
- "early design" https://github.com/w3ctag/design-reviews/issues/735 which was resolved positively
- "specification review" https://github.com/w3ctag/design-reviews/issues/838 

And this TAG review that specifically focuses on [local unpartitioned data access rendering](https://github.com/WICG/fenced-frame/blob/master/explainer/use_cases.md#personalizing-document-content-with-local-unpartitioned-data-access)

If it is recommended to instead converge this issue with https://github.com/w3ctag/design-reviews/issues/838 to review all use cases together, we could do that.

**Comment by jyasskin** [comment]
The TAG agrees that it would be useful to enable the user-focused use case here. Specifically, the web is in the situation that sites show a list of third-party providers, each of which might or might not be able to help the user sign in, pay, or perform some other function on the main site. The user may not remember which of those providers they've stored the relevant data with, and it's frustrating to click one of these buttons only to find that it can't help you. In a browser with 3p cookies, those buttons can give an indication of what data they have access to, but as browsers [phase that out](https://www.w3.org/2001/tag/doc/web-without-3p-cookies/), this sort of button can no longer provide these capabilities. It seems useful to try to prevent that frustration, if doing so is possible without confusing users about what [identity they've already presented to the main site](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context).

The explainer is very unclear about whether that use case is actually the fundamental goal of this proposal. If the explainer is literally correct that the goal is to "decorate a third-party widget with cross-site information about the user", we think that's very likely to be a **harmful** goal and incompatible with our work on privacy principles for the web.

Even if we've correctly understood the use case, we think the proposed solution in this feature makes it too hard for users to correctly infer who already has access to that information. If a user incorrectly infers that the containing site already knows their identity, they're more likely to then "agree" to share their identity with the site, violating the [privacy principle on identity](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context). The [two concrete examples of when to use this feature](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#introduction-and-goals) appear to be causing this sort of mistake in practice, whether or not their designers intended the deception. 


For example, Google Accounts presents a login chip on a number of websites (such as [Reddit](https://www.reddit.com/)). [Some versions of this chip](https://developers.google.com/identity/gsi/web/guides/offerings#one_tap) show your Google account name, profile image, and email address. Several members of the TAG have concluded from this UI that they had already used Google to log into a site, even though they hadn't. We then clicked through the login chip, creating a connection between Google and the site that we hadn't intended or wanted. Even if it wasn't intentional on the part of the UI designers, this had the effect of reducing our [autonomy](https://w3ctag.github.io/privacy-principles/#autonomy). FedCM seems like a better solution for login than letting the providers embed cross-site data.


Google Pay implemented a button that presents the last four digits of a credit card, taken from the last transaction with that service, even if the transaction was elsewhere on the web. This [greatly improved the rates at which people completed a purchase](https://developers.googleblog.com/en/updated-google-pay-button-increases-click-through-rates/). However, we're concerned that, like in the login case, this increase in purchases might be happening because users incorrectly concluded that they'd already bought something from the active site, and we haven't seen UX research that explored users' beliefs in this case. Further work on [Payment Handlers](https://github.com/w3ctag/design-reviews/issues/231) might be a better way to expose this sort of hint.


We don't mean to imply that Google is unusual in these practices. These techniques lead to better business outcomes for websites and their service providers, and it's perhaps unsurprising that neither group has checked what fraction of users are getting the outcomes they want. But we need that evidence before considering this UI in [user agents](https://w3ctag.github.io/design-principles/#priority-of-constituencies). And these are just the relatively benign cases: once a browser removes 3p cookies, truly malicious actors have a much stronger incentive to find ways to trick users into joining their identities (see some ideas in https://github.com/WICG/turtledove/issues/990). This proposal doesn't analyze or protect against that risk.


One might argue that the proposal is ok because it just allows websites to give their users false beliefs, and a user has to still separately consent before their private information is released, but as far as we can tell, identities can be joined as soon as the user clicks, which isn't sufficient for the browser to know they've consented. Even if there were a separate consent screen, its task seems very difficult, needing to both explain what the user's being asked to consent to, and override anything the user's been convinced to believe about what information the site already has.


We suspect that embedding information from a different context inherently enables deception about the surrounding site's knowledge. Certainly embedded sites could do the work of explaining what information their embedders already have, but we've seen that the default behavior is not to do that, and we _haven't_ seen either what malicious actors could do with this when motivated, or a creative analysis of the worst abuse cases. If you intend to pursue something akin to this general approach, a thorough analysis of the ways in which this might be abused and mitigated is essential.


We want to reiterate that the core use case seems valuable to solve, and we encourage you to keep trying to solve it. To do this safely, we suspect that you'll need to show the available information in browser UI, rather than inside the content area.

**Comment by shivanigithub** [comment]
> 
> One might argue that the proposal is ok because it just allows websites to give their users false beliefs, and a user has to still separately consent before their private information is released, but as far as we can tell, identities can be joined as soon as the user clicks, which isn't sufficient for the browser to know they've consented. Even if there were a separate consent screen, its task seems very difficult, needing to both explain what the user's being asked to consent to, and override anything the user's been convinced to believe about what information the site already has.
> 

Could you elaborate on the understanding that a click would be sufficient for identities to be joined with the fenced frames solution?
It's an explicit design goal to not be able to exfiltrate the data read within the fenced frames to the embedding page or to the network. Post-click, the embedding context knows there was a click and the action they take would be independent of what was displayed in the fenced frame, e.g. opening a new pop-up or invoking PaymentHandler etc.

**Comment by martinthomson** [comment]
As I understand it, something happens when someone clicks on the frame.  So there is a difference between an outcome where someone clicks and when someone doesn't.  The embedding contexts learns about whether there was a click.

If the content shown can affect whether a click occurs, then the embedding context gains information.  In the extreme, you might imagine content in the frame that guarantees a click in one case ("click here to enable this free addon") and guarantees no click in another (leaving the area blank or "click here to agree to something awful"), then the information carried by that click (or absence thereof) is high.  Maybe it's not perfect, because people are often perverse like that, but you have created a means of exfiltration.

https://github.com/WICG/turtledove/issues/990 goes into more detail about the sorts of things you might do to gain information from the human involved.

**Comment by jyasskin** [comment]
We can't say "identities can be joined as soon as the user clicks" if we mean "one bit leaks for each click".

I'd missed that the fenced frame can't itself open a popup at an arbitrary URL. https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#information-flow-and-design says the surrounding page has to decide what URL to open. Since that has no more information than an `<a href>`, and I don't see a reason that nav-tracking mitigations (to the extent they're possible at all) won't apply across both, it doesn't seem like this violates the ["leave the web better" principle](https://w3ctag.github.io/design-principles/#leave-the-web-better).

This still puts a lot of responsibility on whatever consent screen appears behind that popup: if users have concluded that the surrounding page already knows their cross-site identity, the consent screen has to counteract that in order to [get an accuration notion of the user's intent](https://w3ctag.github.io/privacy-principles/#principle-consent-user-preference). Is that plausible?

**Comment by shivanigithub** [comment]
> If the content shown can affect whether a click occurs, then the embedding context gains information. In the extreme, you might imagine content in the frame that guarantees a click in one case ("click here to enable this free addon") and guarantees no click in another (leaving the area blank or "click here to agree to something awful"), then the information carried by that click (or absence thereof) is high. Maybe it's not perfect, because people are often perverse like that, but you have created a means of exfiltration.
> 
> [WICG/turtledove#990](https://github.com/WICG/turtledove/issues/990) goes into more detail about the sorts of things you might do to gain information from the human involved.

Responded to the linked issue https://github.com/WICG/turtledove/issues/990#issuecomment-2511630560 with the mitigations for these attacks, ranging from visited links (which is observable w/o user action) to the grid attack (where multiple fenced frames are shown to the user and clicking on one presents some information).
The captcha style attack is one which does not depend on any click in the FF so has a different underlying threat model, but also requires more concerted action on behalf of the user.

**Comment by shivanigithub** [comment]
Since the earlier responses https://github.com/w3ctag/design-reviews/issues/975#issuecomment-2504251335 and https://github.com/w3ctag/design-reviews/issues/975#issuecomment-2509431873 already address the part of the feedback about click information flow, this response mainly addresses the other part of the feedback which is about user perception.

> The TAG agrees that it would be useful to enable the user-focused use case here. Specifically, the web is in the situation that sites show a list of third-party providers, each of which might or might not be able to help the user sign in, pay, or perform some other function on the main site. The user may not remember which of those providers they've stored the relevant data with, and it's frustrating to click one of these buttons only to find that it can't help you. In a browser with 3p cookies, those buttons can give an indication of what data they have access to, but as browsers [phase that out](https://www.w3.org/2001/tag/doc/web-without-3p-cookies/), this sort of button can no longer provide these capabilities. It seems useful to try to prevent that frustration, if doing so is possible without confusing users about what [identity they've already presented to the main site](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context).
> 
> The explainer is very unclear about whether that use case is actually the fundamental goal of this proposal. If the explainer is literally correct that the goal is to "decorate a third-party widget with cross-site information about the user", we think that's very likely to be a **harmful** goal and incompatible with our work on privacy principles for the web.

Yes, indeed the goal is to help users make an informed choice. The explainer is now updated to clarify why cross-site data being presented in a fenced frame would be helpful to the user, specifically that showing personalized information gives the user more context about what they can expect will happen when they click on the button, allowing them to make a more informed choice, closer to their preferences.

> 
> Even if we've correctly understood the use case, we think the proposed solution in this feature makes it too hard for users to correctly infer who already has access to that information. If a user incorrectly infers that the containing site already knows their identity, they're more likely to then "agree" to share their identity with the site, violating the [privacy principle on identity](https://w3ctag.github.io/privacy-principles/#principle-identity-per-context). The [two concrete examples of when to use this feature](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#introduction-and-goals) appear to be causing this sort of mistake in practice, whether or not their designers intended the deception.

This issue of user perception has been brought up in other contexts as well, e.g. for [FedCM](https://github.com/mozilla/standards-positions/issues/618#issuecomment-2452554520:~:text=This%20is%20a%20legitimate%20point) and is a reasonable point of browser design disagreement. Chrome believes that, given the privacy characteristics of this feature, the [supportive feedback](https://github.com/w3ctag/design-reviews/issues/735#issuecomment-1206075921) from ecosystem partners, and the  beneficial use cases for the user and the ecosystem, it is pertinent to move forward with this functionality.

> 
> For example, Google Accounts presents a login chip on a number of websites (such as [Reddit](https://www.reddit.com/)). [Some versions of this chip](https://developers.google.com/identity/gsi/web/guides/offerings#one_tap) show your Google account name, profile image, and email address. Several members of the TAG have concluded from this UI that they had already used Google to log into a site, even though they hadn't. We then clicked through the login chip, creating a connection between Google and the site that we hadn't intended or wanted. Even if it wasn't intentional on the part of the UI designers, this had the effect of reducing our [autonomy](https://w3ctag.github.io/privacy-principles/#autonomy). FedCM seems like a better solution for login than letting the providers embed cross-site data.
> 
To clarify, this functionality is different from the example mentioned above. All that this functionality encourages is a user click, but note that even in the event of a click, _no sharing of cross-site data happens_ directly with the context outside the fenced frame or with the network. Any access to cross-site data has to be via the consuming API’s user interface in the embedding frame e.g. payment workflows, FedCM/login workflows, storage access prompt etc.

> Google Pay implemented a button that presents the last four digits of a credit card, taken from the last transaction with that service, even if the transaction was elsewhere on the web. This [greatly improved the rates at which people completed a purchase](https://developers.googleblog.com/en/updated-google-pay-button-increases-click-through-rates/). However, we're concerned that, like in the login case, this increase in purchases might be happening because users incorrectly concluded that they'd already bought something from the active site, and we haven't seen UX research that explored users' beliefs in this case. Further work on [Payment Handlers](https://github.com/w3ctag/design-reviews/issues/231) might be a better way to expose this sort of hint.
> 
Payment buttons and similar personalized content are an established pattern on the web that users have experienced for a long time. Previously this more informed user experience came with a loss in privacy. This proposal aims to establish a private alternative that preserves an otherwise familiar experience for users.

> We don't mean to imply that Google is unusual in these practices. These techniques lead to better business outcomes for websites and their service providers, and it's perhaps unsurprising that neither group has checked what fraction of users are getting the outcomes they want. But we need that evidence before considering this UI in [user agents](https://w3ctag.github.io/design-principles/#priority-of-constituencies). And these are just the relatively benign cases: once a browser removes 3p cookies, truly malicious actors have a much stronger incentive to find ways to trick users into joining their identities (see some ideas in [WICG/turtledove#990](https://github.com/WICG/turtledove/issues/990)). This proposal doesn't analyze or protect against that risk.

Addressed this point in the above [comment](https://github.com/w3ctag/design-reviews/issues/975#issuecomment-2523539706) and the linked issue’s comment:  [WICG/turtledove#990 (comment)](https://github.com/WICG/turtledove/issues/990#issuecomment-2511630560). To add to those points, Chrome is also requiring this functionality to be gated by the site being [enrolled and attested for Privacy Sandbox](https://developers.google.com/privacy-sandbox/private-advertising/enrollment).

**Comment by martinthomson** [comment]
@shivanigithub, I don't think that your response really addresses the feedback.  You might claim that presenting additional information could improve the information that a user has in making choices, which is objectively true.  However, the primary concern is about the potential for deception.  Arguably, the Google Pay example is both improving information presentation AND a deceptive practice at the same time, so this is not mutually exclusive.

> even in the event of a click, no sharing of cross-site data happens

I do not agree with this claim.

**Comment by martinthomson** [comment]
> are you arguing that these well-established (and very common) third-party payment widgets are deceptive / harmful for users on the web?

Well-established is debatable (given that this specific behavior is impossible in most browsers, modulo the one that allows tracking).

But yes, this enables deception.  I can't present empirical evidence of harm, but that's not the standard that applies here.  Those presenting the new concept need to present evidence that harm is absent or at least mitigated such that the benefit more than outweighs the harm.

It is not only the "positive" use cases that need to be considered in that analysis (for the record, I don't regard either of these as positive, they are both not-so-subtly manipulative, but that's my own subjective view).  This has to consider the potential for the feature to be used maliciously.

> What I believe Shivani meant is that there is no additional information that a Fenced Frame could contribute here vs. any other element on the page, thus not changing the status quo. Am I correct here?

I am saying that Shivani's assertion is incorrect when you consider that webpages are shown to people[^1].

[^1] I can't even imagine what this could do to an agentic AI. Maybe nothing, because the agent might not care about privacy in the same way that they don't care about anything.  Either way, that's not the issue in question, so we don't have to consider it for the moment.

Let me give you a simple example: there is one bit of information available to the fenced frame.  That bit could mean anything, but let's say that it corresponds to some private trait, known to the third party and not the current page.  

A site could use two of these fenced frames, using that bit to decide which gets to be rendered as completely blank and which gets to be rendered as something that is highly likely to result in a click.  There are lots of things that people routinely click on in certain contexts, this is not special.  How about this:

![Image](https://github.com/user-attachments/assets/fd2211b9-846b-41f9-b2e2-684e47c96e15)

vs.

![Image](https://github.com/user-attachments/assets/8ae4fc25-b500-47eb-8472-3c88de1d97e7)

That is, both buttons shift depending on the value of that bit.  It's pretty unsubtle, but this arrangement virtually guarantees a click in the location that has content (users with screen readers are potentially duped, but I'm less clear on what you might do to deceive them this way).  The site then learns the value of the bit with high certainty.

The [Protected Audience issue thread](https://github.com/WICG/turtledove/issues/990) explores other attack modalities.

**Comment by shivanigithub** [comment]
Hey folks,
To clarify, the earlier assertion on "_no sharing of cross-site data happens_ directly with the context outside the fenced frame" is about the way the API is designed. The API itself doesn't expose any metadata about the click which could encode cross-site data. However, covert channels could be created via a click and Martin's example above is what I have mentioned in point (2) in the linked [issue](https://github.com/WICG/turtledove/issues/990#issuecomment-2511630560) . Adding that response here for completeness:
**clicking on a given frame out of a grid of frames:** This is in our threat model and we are working on a solution to this, as part of the new [window.fence.notifyEvent API](https://github.com/WICG/fenced-frame/blob/master/explainer/fenced_frames_with_local_unpartitioned_data_access.md#changes-to-windowfence). Rate limiting the number of related fenced frames that the user can see will help these kind of attacks and we will update the explainer (and here), once the design is more fleshed out with the details of those rate limits.
