### ISSUE TITLE
WebXR Device API (delta/aiming 2nd CRS)

### ISSUE THREAD

**Issue by himorin** [w3ctag/design-reviews#983]
こんにちは TAG-さん!

I'm requesting a TAG review of [WebXR Device API](https://www.w3.org/TR/2024/CRD-webxr-20240805/).

This specification describes support for accessing virtual reality (VR) and augmented reality (AR) devices, including sensors and head-mounted displays, on the Web.

  - Explainer¹ (minimally containing user needs and example code): [Overall WebXR explainer](https://github.com/immersive-web/webxr/blob/main/explainer.md)
  - Specification URL: [url](https://www.w3.org/TR/2024/CRD-webxr-20240805/)
  - Tests: [wpt webxr](https://wpt.fyi/results/webxr?label=master&label=experimental&aligned)
  - User research: n/a
  - Security and Privacy self-review²: https://github.com/immersive-web/webxr/issues/1379
  - GitHub repo: https://github.com/immersive-web/webxr/
  - Primary contacts (and their relationship to the specification):
      - Brandon Jones (@toji), Google, Editor
      - Manish Goregaokar, (@Manishearth), Google, Editor
      - Rik Cabanier (@cabanier), Meta, Editor
      - Ada Rose Cannon (@AdaRoseCannon), Apple, Chair
      - Chris Wilson (@cwilso), Google, Chair
      - Ayşegül Yönet (@Yonet), IE, Chair
  - Organization(s)/project(s) driving the specification: Immersive Web WG
  - Key pieces of existing multi-stakeholder (e.g. developers, implementers, civil society) support, review or discussion of this specification
  - Key pieces of multi-implementer support:
    - previous whole review for [1st CRS](https://github.com/w3c/transitions/issues/420) https://github.com/w3ctag/design-reviews/issues/545
    - CRdelta review https://github.com/w3ctag/design-reviews/issues/782
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status):
    - https://chromestatus.com/feature/5680169905815552
    - https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API#browser_compatibility

Further details:

  - [x] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: Expecting to update existing CRS, no specific target date
  - The group where the work on this specification is currently being done: Immersive Web WG
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): n/a
  - Major unresolved issues with or opposition to this specification: no
  - This work is being funded by:

You should also know that...

[changes from 1st CRS is listed in specification](https://www.w3.org/TR/2024/CRD-webxr-20240805/#changes-from-20220331), and we've got TAG review for [first one](https://github.com/immersive-web/webxr/pull/1296) at https://github.com/w3ctag/design-reviews/issues/782
We'd like to get review over remaining five substantive changes: https://github.com/immersive-web/webxr/pull/1314 https://github.com/immersive-web/webxr/pull/1332 https://github.com/immersive-web/webxr/pull/1343 https://github.com/immersive-web/webxr/pull/1353 https://github.com/immersive-web/webxr/pull/1359

**Comment by matatk** [comment]
Thanks for your review request&mdash;and for highlighting the changes since last time. Here are a few comments on these changes.

HT @m-alkalbani for assisting with the review.

1. Expose XRSession&rsquo;s granted features ([GitHub \#1296](https://github.com/immersive-web/webxr/pull/1296))

   Looks good!

2. Add support for the isSystemKeyboardSupported attribute ([GitHub \#1314](https://github.com/immersive-web/webxr/pull/1314))

   This Boolean's name starts with 'is' whereas others' names don't seem to. Is there a reason for this, such as consistency with other specs? It seems inconsistent with other parts of WebXR Device API.

3. Clarify getPose behavior with visibile-blurred ([GitHub \#1332](https://github.com/immersive-web/webxr/pull/1332))

   Looks good!

4. Transient intent addition ([GitHub \#1343](https://github.com/immersive-web/webxr/pull/1343))

   This looks good &mdash; but gave rise to a question about an instance of one of the terms used in the [definition of `targetRayMode` enum values](https://www.w3.org/TR/2024/CRD-webxr-20240805/#dom-xrinputsource-targetraymode)...

   Assuming that the `gaze` enum variant is talking about getting input from the direction someone's head is facing...

   The [definition for the `transient-pointer` enum variant](https://www.w3.org/TR/2024/CRD-webxr-20240805/#dom-xrtargetraymode-transient-pointer) states: "Some examples are user intents based on information too sensitive to expose directly such as gaze..." &mdash; however in this phrase, is "gaze" actually referring to input that comes from _eye_ gaze (i.e. eye tracking)? If so, the word "gaze" is referring to two differnet things; would you be able to re-phrase this to make that clear?

5. First draft for adding a property to XRInputSource to say it&rsquo;s visible elsewhere ([GitHub \#1353](https://github.com/immersive-web/webxr/pull/1353))

   This looks good &mdash; but the PR referenced here should be 1352, so the Changes section should be updated.

6. Clarify rgb vs srgb behavior ([GitHub \#1359](https://github.com/immersive-web/webxr/pull/1359))

   We want to keep reminding people to try to align colors between CSS, canvas, and the other drawing surfaces in the platform. That said, that's a long-term project, and we don't expect this incremental change to solve it. Otherwise looks good!

Also...

7. [The definition for `transient-pointer`](https://www.w3.org/TR/2024/CRD-webxr-20240805/#dom-xrtargetraymode-transient-pointer) has a typo; it mentions "W3C design principals" &mdash; I think you mean to reference [Web Design Principle 2.9: Don’t reveal that assistive technologies are being used](https://www.w3.org/TR/design-principles/#do-not-expose-use-of-assistive-tech); if so, perhaps you could include this link.

   That you made the reference, and read the principles, is appreciated!
